apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: easi-frontend
  name: easi-frontend
  namespace: easi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: easi-frontend
  template:
    metadata:
      labels:
        app: easi-frontend
    spec:
      containers:
        - name: easi-frontend
          image: easi-frontend:latest
          imagePullPolicy: Never
          envFrom:
            - configMapRef:
                name: easi-frontend-configmap
          ports:
            - containerPort: 3000
              protocol: TCP
          resources: {}
      restartPolicy: Always
