apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: easi-frontend
  name: easi-frontend
  namespace: easi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: easi-frontend
  template:
    metadata:
      labels:
        app: easi-frontend
    spec:
      volumes:
      - name: nginx-config
        configMap:
          name: easi-frontend-configmap-nginx
      containers:
        - name: easi-frontend
          image: easi-frontend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
              protocol: TCP
          resources: {}
          volumeMounts:
          - name: nginx-config
            mountPath: /etc/nginx/conf.d/easi.conf
            subPath: easi.conf
      restartPolicy: Always
