apiVersion: v1
kind: Service
metadata:
  name: email
  namespace: easi
spec:
  ports:
    - name: "smtp"
      port: 1025
      targetPort: 1025
    - name: "http"
      port: 1080
      targetPort: 1080
  selector:
    app: email
