package cedarcoremock

import (
	"time"

	"github.com/guregu/null/zero"

	"github.com/cms-enterprise/easi-app/pkg/models"
)

var mockDeployments = []*models.CedarDeployment{
	{
		ID:                       zero.StringFrom("{11AB1A00-1234-5678-ABC1-1A001B00CC0A}"),
		Name:                     zero.StringFrom("Accountable Care Organization-Operational System (Development)"),
		SystemID:                 zero.StringFrom("{11AB1A00-1234-5678-ABC1-1A001B00CC0A}"),
		StartDate:                zero.TimeFrom(time.Time{}),
		EndDate:                  zero.TimeFrom(time.Time{}),
		IsHotSite:                zero.StringFrom("No"),
		Description:              zero.StringFrom(""),
		ContractorName:           zero.StringFrom("Leidos"),
		SystemVersion:            zero.StringFrom("Leidos"),
		HasProductionData:        zero.StringFrom("No"),
		ReplicatedSystemElements: []string{},
		DeploymentType:           zero.StringFrom("Development"),
		SystemName:               zero.StringFrom("Information Systems Team"),
		DeploymentElementID:      zero.StringFrom("{11AB1A00-1234-5678-ABC1-1A001B00CC0A}"),
		State:                    zero.StringFrom("active"),
		Status:                   zero.StringFrom("draft"),
		WanType:                  zero.StringFrom("CMSNet|Internet - CMS"),
		DataCenter: &models.CedarDataCenter{
			ID:           zero.StringFrom("{11AB1A00-1234-5678-ABC1-1A001B00CC0A}"),
			Name:         zero.StringFrom("CMS Culpeper Data Center - EDC4"),
			Version:      zero.StringFrom("1"),
			Description:  zero.StringFrom("Location"),
			State:        zero.StringFrom("active"),
			Status:       zero.StringFrom("approved"),
			StartDate:    zero.TimeFrom(time.Time{}),
			EndDate:      zero.TimeFrom(time.Time{}),
			Address1:     zero.StringFrom("123 Main Street"),
			Address2:     zero.StringFrom(""),
			City:         zero.StringFrom("Culpeper"),
			AddressState: zero.StringFrom("VIRGINIA (VA)"),
			Zip:          zero.StringFrom("57105"),
		},
	},
	{
		ID:                       zero.StringFrom("{11AB1A00-1234-5678-ABC1-1A001B00CC1B}"),
		Name:                     zero.StringFrom("Accountable Care Organization-Operational System (Implementation)"),
		SystemID:                 zero.StringFrom("{11AB1A00-1234-5678-ABC1-1A001B00CC1B}"),
		StartDate:                zero.TimeFrom(time.Time{}),
		EndDate:                  zero.TimeFrom(time.Time{}),
		IsHotSite:                zero.StringFrom("Yes"),
		Description:              zero.StringFrom(""),
		ContractorName:           zero.StringFrom("AWS"),
		SystemVersion:            zero.StringFrom("AWS"),
		HasProductionData:        zero.StringFrom("Yes"),
		ReplicatedSystemElements: []string{},
		DeploymentType:           zero.StringFrom("Implementation"),
		SystemName:               zero.StringFrom("Information Systems Team"),
		DeploymentElementID:      zero.StringFrom("{11AB1A00-1234-5678-ABC1-1A001B00CC1B}"),
		State:                    zero.StringFrom("active"),
		Status:                   zero.StringFrom("draft"),
		WanType:                  zero.StringFrom("CMSNet"),
		DataCenter: &models.CedarDataCenter{
			ID:           zero.StringFrom("{11AB1A00-1234-5678-ABC1-1A001B00CC1B}"),
			Name:         zero.StringFrom("CMS Phoenix Data Center - EDC4"),
			Version:      zero.StringFrom("2"),
			Description:  zero.StringFrom("Location"),
			State:        zero.StringFrom("retired"),
			Status:       zero.StringFrom("draft"),
			StartDate:    zero.TimeFrom(time.Time{}),
			EndDate:      zero.TimeFrom(time.Time{}),
			Address1:     zero.StringFrom("123 Main Street"),
			Address2:     zero.StringFrom(""),
			City:         zero.StringFrom("Phoenix"),
			AddressState: zero.StringFrom("ARIZONA (AZ)"),
			Zip:          zero.StringFrom("09876"),
		},
	},
	{
		ID:                       zero.StringFrom("{11AB1A00-1234-5678-ABC1-1A001B00CC2C}"),
		Name:                     zero.StringFrom("Accountable Care Organization-Operational System (Production)"),
		SystemID:                 zero.StringFrom("{11AB1A00-1234-5678-ABC1-1A001B00CC2C}"),
		StartDate:                zero.TimeFrom(time.Time{}),
		EndDate:                  zero.TimeFrom(time.Time{}),
		IsHotSite:                zero.StringFrom("No"),
		Description:              zero.StringFrom(""),
		ContractorName:           zero.StringFrom("BDS"),
		SystemVersion:            zero.StringFrom("BDS"),
		HasProductionData:        zero.StringFrom("No"),
		ReplicatedSystemElements: []string{},
		DeploymentType:           zero.StringFrom("Production"),
		SystemName:               zero.StringFrom("Information Systems Team"),
		DeploymentElementID:      zero.StringFrom("{11AB1A00-1234-5678-ABC1-1A001B00CC2C}"),
		State:                    zero.StringFrom("retired"),
		Status:                   zero.StringFrom("draft"),
		WanType:                  zero.StringFrom("CMSNet"),
		DataCenter: &models.CedarDataCenter{
			ID:           zero.StringFrom("{11AB1A00-1234-5678-ABC1-1A001B00CC2C}"),
			Name:         zero.StringFrom("CMS Eureka Data Center - EDC4"),
			Version:      zero.StringFrom("3"),
			Description:  zero.StringFrom("Location"),
			State:        zero.StringFrom("planned"),
			Status:       zero.StringFrom("approved"),
			StartDate:    zero.TimeFrom(time.Time{}),
			EndDate:      zero.TimeFrom(time.Time{}),
			Address1:     zero.StringFrom("123 Main Street"),
			Address2:     zero.StringFrom(""),
			City:         zero.StringFrom("Eureka"),
			AddressState: zero.StringFrom("CALIFORNIA (CA)"),
			Zip:          zero.StringFrom("33445"),
		},
	},
	{
		ID:                       zero.StringFrom("{11AB1A00-1234-5678-ABC1-1A001B00CC3D}"),
		Name:                     zero.StringFrom("Accountable Care Organization-Operational System (Testing)"),
		SystemID:                 zero.StringFrom("{11AB1A00-1234-5678-ABC1-1A001B00CC3D}"),
		StartDate:                zero.TimeFrom(time.Time{}),
		EndDate:                  zero.TimeFrom(time.Time{}),
		IsHotSite:                zero.StringFrom("Yes"),
		Description:              zero.StringFrom(""),
		ContractorName:           zero.StringFrom("test"),
		SystemVersion:            zero.StringFrom("test"),
		HasProductionData:        zero.StringFrom("Yes"),
		ReplicatedSystemElements: []string{},
		DeploymentType:           zero.StringFrom("Testing"),
		SystemName:               zero.StringFrom("Managerial Mission Management"),
		DeploymentElementID:      zero.StringFrom("{11AB1A00-1234-5678-ABC1-1A001B00CC3D}"),
		State:                    zero.StringFrom("planned"),
		Status:                   zero.StringFrom("approved"),
		WanType:                  zero.StringFrom("CMSNet|Internet - CMS"),
		DataCenter: &models.CedarDataCenter{
			ID:           zero.StringFrom("{11AB1A00-1234-5678-ABC1-1A001B00CC3D}"),
			Name:         zero.StringFrom("CMS Detroit Data Center - EDC4"),
			Version:      zero.StringFrom("4"),
			Description:  zero.StringFrom("Location"),
			State:        zero.StringFrom("active"),
			Status:       zero.StringFrom("draft"),
			StartDate:    zero.TimeFrom(time.Time{}),
			EndDate:      zero.TimeFrom(time.Time{}),
			Address1:     zero.StringFrom("123 Main Street"),
			Address2:     zero.StringFrom(""),
			City:         zero.StringFrom("Detroit"),
			AddressState: zero.StringFrom("MICHIGAN (MI)"),
			Zip:          zero.StringFrom("67890"),
		},
	},
	{
		ID:                       zero.StringFrom("{11AB1A00-1234-5678-ABC1-1A001B00CC4E}"),
		Name:                     zero.StringFrom("Accountable Care Organization-Operational System (COOP DR)"),
		SystemID:                 zero.StringFrom("{11AB1A00-1234-5678-ABC1-1A001B00CC4E}"),
		StartDate:                zero.TimeFrom(time.Time{}),
		EndDate:                  zero.TimeFrom(time.Time{}),
		IsHotSite:                zero.StringFrom("No"),
		Description:              zero.StringFrom(""),
		ContractorName:           zero.StringFrom("Leidos"),
		SystemVersion:            zero.StringFrom("Leidos"),
		HasProductionData:        zero.StringFrom("No"),
		ReplicatedSystemElements: []string{},
		DeploymentType:           zero.StringFrom("COOP DR"),
		SystemName:               zero.StringFrom("Center for Central Centrifugal Certainty"),
		DeploymentElementID:      zero.StringFrom("{11AB1A00-1234-5678-ABC1-1A001B00CC4E}"),
		State:                    zero.StringFrom("retired"),
		Status:                   zero.StringFrom("approved"),
		WanType:                  zero.StringFrom("Internet - Contractor"),
		DataCenter: &models.CedarDataCenter{
			ID:           zero.StringFrom("{11AB1A00-1234-5678-ABC1-1A001B00CC4E}"),
			Name:         zero.StringFrom("CMS St. Louis Data Center - EDC4"),
			Version:      zero.StringFrom("5"),
			Description:  zero.StringFrom("Location"),
			State:        zero.StringFrom("planned"),
			Status:       zero.StringFrom("approved"),
			StartDate:    zero.TimeFrom(time.Time{}),
			EndDate:      zero.TimeFrom(time.Time{}),
			Address1:     zero.StringFrom("123 Main Street"),
			Address2:     zero.StringFrom(""),
			City:         zero.StringFrom("St. Louis"),
			AddressState: zero.StringFrom("MISSOURI (MO)"),
			Zip:          zero.StringFrom("12345"),
		},
	},
}

func GetDeployments() []*models.CedarDeployment {
	return mockDeployments
}
