package cedarcoremock

import (
	"time"

	"github.com/guregu/null/zero"

	"github.com/cms-enterprise/easi-app/pkg/models"
)

var mockExchanges = map[string][]*models.CedarExchange{
	"{11AB1A00-1234-5678-ABC1-1A001B00CC0A}": {
		{
			ConnectionFrequency:         []zero.String{zero.StringFrom("Ad Hoc"), zero.StringFrom("As Needed")},
			ContainsBankingData:         true,
			ContainsBeneficiaryAddress:  true,
			ContainsPhi:                 true,
			ContainsPii:                 true,
			ContainsHealthDisparityData: true,
			DataExchangeAgreement:       zero.StringFrom("No agreement on file"),
			DataFormat:                  zero.StringFrom("JSON"),
			DataFormatOther:             zero.StringFrom(""),
			ExchangeDescription:         zero.StringFrom("Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat."),
			ExchangeEndDate:             zero.TimeFrom(time.Time{}),
			ExchangeID:                  zero.StringFrom("{11AB1A00-1234-5678-ABC1-1A001B00CC0A}"),
			ExchangeName:                zero.StringFrom("IT Project Business Cases"),
			ExchangeRetiredDate:         zero.TimeFrom(time.Time{}),
			ExchangeStartDate:           zero.TimeFrom(time.Time{}),
			ExchangeState:               zero.StringFrom("Active"),
			ExchangeVersion:             zero.StringFrom("24"),
			ExchangeDirection:           models.ExchangeDirectionReceiver,
			FromOwnerID:                 zero.StringFrom("{11AB1A00-1234-5678-ABC1-1A001B00CC0A}"),
			FromOwnerName:               zero.StringFrom("CMS Enterprise Data Analytics Repository"),
			FromOwnerType:               zero.StringFrom("System"),
			IsBeneficiaryMailingFile:    true,
			NumOfRecords:                zero.StringFrom("< 1000"),
			SharedViaAPI:                true,
			ToOwnerID:                   zero.StringFrom("{11AB1A00-1234-5678-ABC1-1A001B00CC0A}"),
			ToOwnerName:                 zero.StringFrom("Easy Access to System Information"),
			ToOwnerType:                 zero.StringFrom("System"),
			TypeOfData: []*models.CedarExchangeTypeOfDataItem{{
				ID:   zero.StringFrom("{11AB1A00-1234-5678-ABC1-1A001B00CC0A}"),
				Name: zero.StringFrom("Information Resources"),
			}},
		},
		{
			ConnectionFrequency:         []zero.String{zero.StringFrom("Ad Hoc"), zero.StringFrom("As Needed")},
			ContainsBankingData:         false,
			ContainsBeneficiaryAddress:  false,
			ContainsPhi:                 false,
			ContainsPii:                 false,
			ContainsHealthDisparityData: false,
			DataExchangeAgreement:       zero.StringFrom("System Interconnectivity Document of Understanding (SIDU)"),
			DataFormat:                  zero.StringFrom("YAML"),
			DataFormatOther:             zero.StringFrom(""),
			ExchangeDescription:         zero.StringFrom("Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat."),
			ExchangeEndDate:             zero.TimeFrom(time.Time{}),
			ExchangeID:                  zero.StringFrom("{11AB1A00-1234-5678-ABC1-1A001B00CC0A}"),
			ExchangeName:                zero.StringFrom("IT Project Business Cases 2"),
			ExchangeRetiredDate:         zero.TimeFrom(time.Time{}),
			ExchangeStartDate:           zero.TimeFrom(time.Time{}),
			ExchangeState:               zero.StringFrom("Active"),
			ExchangeVersion:             zero.StringFrom("20"),
			ExchangeDirection:           models.ExchangeDirectionSender,
			FromOwnerID:                 zero.StringFrom("{11AB1A00-1234-5678-ABC1-1A001B00CC0A}"),
			FromOwnerName:               zero.StringFrom("CMS Enterprise Data Analytics Repository 2"),
			FromOwnerType:               zero.StringFrom("System"),
			IsBeneficiaryMailingFile:    false,
			NumOfRecords:                zero.StringFrom("< 3000"),
			SharedViaAPI:                false,
			ToOwnerID:                   zero.StringFrom("{11AB1A00-1234-5678-ABC1-1A001B00CC0A}"),
			ToOwnerName:                 zero.StringFrom("Easy Access to System Information 3"),
			ToOwnerType:                 zero.StringFrom("System"),
			TypeOfData: []*models.CedarExchangeTypeOfDataItem{{
				ID:   zero.StringFrom("{11AB1A00-1234-5678-ABC1-1A001B00CC0A}"),
				Name: zero.StringFrom("Information Resources 2"),
			}},
		},
	},
	"{11AB1A00-1234-5678-ABC1-1A001B00CC1B}": {
		{
			ConnectionFrequency:         []zero.String{zero.StringFrom("Ad Hoc"), zero.StringFrom("As Needed")},
			ContainsBankingData:         true,
			ContainsBeneficiaryAddress:  true,
			ContainsPhi:                 true,
			ContainsPii:                 true,
			ContainsHealthDisparityData: true,
			DataExchangeAgreement:       zero.StringFrom("Agreement pending"),
			DataFormat:                  zero.StringFrom("TXT"),
			DataFormatOther:             zero.StringFrom(""),
			ExchangeDescription:         zero.StringFrom("Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat."),
			ExchangeEndDate:             zero.TimeFrom(time.Time{}),
			ExchangeID:                  zero.StringFrom("{11AB1A00-1234-5678-ABC1-1A001B00CC1B}"),
			ExchangeName:                zero.StringFrom("IT Project Business Cases"),
			ExchangeRetiredDate:         zero.TimeFrom(time.Time{}),
			ExchangeStartDate:           zero.TimeFrom(time.Time{}),
			ExchangeState:               zero.StringFrom("Retired"),
			ExchangeVersion:             zero.StringFrom("24"),
			ExchangeDirection:           models.ExchangeDirectionReceiver,
			FromOwnerID:                 zero.StringFrom("{11AB1A00-1234-5678-ABC1-1A001B00CC1B}"),
			FromOwnerName:               zero.StringFrom("CMS Enterprise Data Analytics Repository"),
			FromOwnerType:               zero.StringFrom("System"),
			IsBeneficiaryMailingFile:    true,
			NumOfRecords:                zero.StringFrom("100,000 - 1 Million"),
			SharedViaAPI:                true,
			ToOwnerID:                   zero.StringFrom("{11AB1A00-1234-5678-ABC1-1A001B00CC1B}"),
			ToOwnerName:                 zero.StringFrom("Easy Access to System Information"),
			ToOwnerType:                 zero.StringFrom("System"),
			TypeOfData: []*models.CedarExchangeTypeOfDataItem{{
				ID:   zero.StringFrom("{11AB1A00-1234-5678-ABC1-1A001B00CC1B}"),
				Name: zero.StringFrom("Information Resources"),
			}},
		},
		{
			ConnectionFrequency:         []zero.String{zero.StringFrom("Ad Hoc"), zero.StringFrom("As Needed")},
			ContainsBankingData:         false,
			ContainsBeneficiaryAddress:  false,
			ContainsPhi:                 false,
			ContainsPii:                 false,
			ContainsHealthDisparityData: false,
			DataExchangeAgreement:       zero.StringFrom("System Interconnectivity Document of Understanding (SIDU)"),
			DataFormat:                  zero.StringFrom("YAML"),
			DataFormatOther:             zero.StringFrom(""),
			ExchangeDescription:         zero.StringFrom("Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat."),
			ExchangeEndDate:             zero.TimeFrom(time.Time{}),
			ExchangeID:                  zero.StringFrom("{11AB1A00-1234-5678-ABC1-1A001B00CC1B}"),
			ExchangeName:                zero.StringFrom("IT Project Business Cases 2"),
			ExchangeRetiredDate:         zero.TimeFrom(time.Time{}),
			ExchangeStartDate:           zero.TimeFrom(time.Time{}),
			ExchangeState:               zero.StringFrom("Paused"),
			ExchangeVersion:             zero.StringFrom("20"),
			ExchangeDirection:           models.ExchangeDirectionSender,
			FromOwnerID:                 zero.StringFrom("{11AB1A00-1234-5678-ABC1-1A001B00CC1B}"),
			FromOwnerName:               zero.StringFrom("CMS Enterprise Data Analytics Repository 2"),
			FromOwnerType:               zero.StringFrom("System"),
			IsBeneficiaryMailingFile:    false,
			NumOfRecords:                zero.StringFrom("< 3,000"),
			SharedViaAPI:                false,
			ToOwnerID:                   zero.StringFrom("{11AB1A00-1234-5678-ABC1-1A001B00CC1B}"),
			ToOwnerName:                 zero.StringFrom("Easy Access to System Information 3"),
			ToOwnerType:                 zero.StringFrom("System"),
			TypeOfData: []*models.CedarExchangeTypeOfDataItem{{
				ID:   zero.StringFrom("{11AB1A00-1234-5678-ABC1-1A001B00CC1B}"),
				Name: zero.StringFrom("Information Resources 2"),
			}},
		},
	},
	"{11AB1A00-1234-5678-ABC1-1A001B00CC2C}": {
		{
			ConnectionFrequency:         []zero.String{zero.StringFrom("Ad Hoc"), zero.StringFrom("As Needed")},
			ContainsBankingData:         true,
			ContainsBeneficiaryAddress:  true,
			ContainsPhi:                 true,
			ContainsPii:                 true,
			ContainsHealthDisparityData: true,
			DataExchangeAgreement:       zero.StringFrom("No agreement on file"),
			DataFormat:                  zero.StringFrom("TXT"),
			DataFormatOther:             zero.StringFrom(""),
			ExchangeDescription:         zero.StringFrom("Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat."),
			ExchangeEndDate:             zero.TimeFrom(time.Time{}),
			ExchangeID:                  zero.StringFrom("{11AB1A00-1234-5678-ABC1-1A001B00CC2C}"),
			ExchangeName:                zero.StringFrom("IT Project Business Cases"),
			ExchangeRetiredDate:         zero.TimeFrom(time.Time{}),
			ExchangeStartDate:           zero.TimeFrom(time.Time{}),
			ExchangeState:               zero.StringFrom("Status unknown"),
			ExchangeVersion:             zero.StringFrom("24"),
			ExchangeDirection:           models.ExchangeDirectionReceiver,
			FromOwnerID:                 zero.StringFrom("{11AB1A00-1234-5678-ABC1-1A001B00CC2C}"),
			FromOwnerName:               zero.StringFrom("CMS Enterprise Data Analytics Repository"),
			FromOwnerType:               zero.StringFrom("System"),
			IsBeneficiaryMailingFile:    true,
			NumOfRecords:                zero.StringFrom("< 1,000"),
			SharedViaAPI:                true,
			ToOwnerID:                   zero.StringFrom("{11AB1A00-1234-5678-ABC1-1A001B00CC2C}"),
			ToOwnerName:                 zero.StringFrom("Easy Access to System Information"),
			ToOwnerType:                 zero.StringFrom("System"),
			TypeOfData: []*models.CedarExchangeTypeOfDataItem{{
				ID:   zero.StringFrom("{11AB1A00-1234-5678-ABC1-1A001B00CC2C}"),
				Name: zero.StringFrom("Information Resources"),
			}},
		},
		{
			ConnectionFrequency:         []zero.String{zero.StringFrom("Ad Hoc"), zero.StringFrom("As Needed")},
			ContainsBankingData:         false,
			ContainsBeneficiaryAddress:  false,
			ContainsPhi:                 false,
			ContainsPii:                 false,
			ContainsHealthDisparityData: false,
			DataExchangeAgreement:       zero.StringFrom("Yes"),
			DataFormat:                  zero.StringFrom("YAML"),
			DataFormatOther:             zero.StringFrom(""),
			ExchangeDescription:         zero.StringFrom("Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat."),
			ExchangeEndDate:             zero.TimeFrom(time.Time{}),
			ExchangeID:                  zero.StringFrom("{11AB1A00-1234-5678-ABC1-1A001B00CC2C}"),
			ExchangeName:                zero.StringFrom("IT Project Business Cases 2"),
			ExchangeRetiredDate:         zero.TimeFrom(time.Time{}),
			ExchangeStartDate:           zero.TimeFrom(time.Time{}),
			ExchangeState:               zero.StringFrom("Status unknown"),
			ExchangeVersion:             zero.StringFrom("20"),
			ExchangeDirection:           models.ExchangeDirectionSender,
			FromOwnerID:                 zero.StringFrom("{11AB1A00-1234-5678-ABC1-1A001B00CC2C}"),
			FromOwnerName:               zero.StringFrom("CMS Enterprise Data Analytics Repository 2"),
			FromOwnerType:               zero.StringFrom("System"),
			IsBeneficiaryMailingFile:    false,
			NumOfRecords:                zero.StringFrom("< 3,000"),
			SharedViaAPI:                false,
			ToOwnerID:                   zero.StringFrom("{11AB1A00-1234-5678-ABC1-1A001B00CC2C}"),
			ToOwnerName:                 zero.StringFrom("Easy Access to System Information 3"),
			ToOwnerType:                 zero.StringFrom("System"),
			TypeOfData: []*models.CedarExchangeTypeOfDataItem{{
				ID:   zero.StringFrom("{11AB1A00-1234-5678-ABC1-1A001B00CC2C}"),
				Name: zero.StringFrom("Information Resources 2"),
			}},
		},
	},
	"{11AB1A00-1234-5678-ABC1-1A001B00CC3D}": {
		{
			ConnectionFrequency:         []zero.String{zero.StringFrom("Ad Hoc"), zero.StringFrom("As Needed")},
			ContainsBankingData:         true,
			ContainsBeneficiaryAddress:  true,
			ContainsPhi:                 true,
			ContainsPii:                 true,
			ContainsHealthDisparityData: true,
			DataExchangeAgreement:       zero.StringFrom("No"),
			DataFormat:                  zero.StringFrom("TXT"),
			DataFormatOther:             zero.StringFrom(""),
			ExchangeDescription:         zero.StringFrom("Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat."),
			ExchangeEndDate:             zero.TimeFrom(time.Time{}),
			ExchangeID:                  zero.StringFrom("{11AB1A00-1234-5678-ABC1-1A001B00CC3D}"),
			ExchangeName:                zero.StringFrom("IT Project Business Cases"),
			ExchangeRetiredDate:         zero.TimeFrom(time.Time{}),
			ExchangeStartDate:           zero.TimeFrom(time.Time{}),
			ExchangeState:               zero.StringFrom("Active"),
			ExchangeVersion:             zero.StringFrom("24"),
			ExchangeDirection:           models.ExchangeDirectionReceiver,
			FromOwnerID:                 zero.StringFrom("{11AB1A00-1234-5678-ABC1-1A001B00CC3D}"),
			FromOwnerName:               zero.StringFrom("CMS Enterprise Data Analytics Repository"),
			FromOwnerType:               zero.StringFrom("System"),
			IsBeneficiaryMailingFile:    true,
			NumOfRecords:                zero.StringFrom("< 1,000"),
			SharedViaAPI:                true,
			ToOwnerID:                   zero.StringFrom("{11AB1A00-1234-5678-ABC1-1A001B00CC3D}"),
			ToOwnerName:                 zero.StringFrom("Easy Access to System Information"),
			ToOwnerType:                 zero.StringFrom("System"),
			TypeOfData: []*models.CedarExchangeTypeOfDataItem{{
				ID:   zero.StringFrom("{11AB1A00-1234-5678-ABC1-1A001B00CC3D}"),
				Name: zero.StringFrom("Information Resources"),
			}},
		},
		{
			ConnectionFrequency:         []zero.String{zero.StringFrom("Ad Hoc"), zero.StringFrom("As Needed")},
			ContainsBankingData:         false,
			ContainsBeneficiaryAddress:  false,
			ContainsPhi:                 false,
			ContainsPii:                 false,
			ContainsHealthDisparityData: false,
			DataExchangeAgreement:       zero.StringFrom("Yes"),
			DataFormat:                  zero.StringFrom("YAML"),
			DataFormatOther:             zero.StringFrom(""),
			ExchangeDescription:         zero.StringFrom("Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat."),
			ExchangeEndDate:             zero.TimeFrom(time.Time{}),
			ExchangeID:                  zero.StringFrom("{11AB1A00-1234-5678-ABC1-1A001B00CC3D}"),
			ExchangeName:                zero.StringFrom("IT Project Business Cases 2"),
			ExchangeRetiredDate:         zero.TimeFrom(time.Time{}),
			ExchangeStartDate:           zero.TimeFrom(time.Time{}),
			ExchangeState:               zero.StringFrom("Retired"),
			ExchangeVersion:             zero.StringFrom("20"),
			ExchangeDirection:           models.ExchangeDirectionSender,
			FromOwnerID:                 zero.StringFrom("{11AB1A00-1234-5678-ABC1-1A001B00CC3D}"),
			FromOwnerName:               zero.StringFrom("CMS Enterprise Data Analytics Repository 2"),
			FromOwnerType:               zero.StringFrom("System"),
			IsBeneficiaryMailingFile:    false,
			NumOfRecords:                zero.StringFrom("< 3,000"),
			SharedViaAPI:                false,
			ToOwnerID:                   zero.StringFrom("{11AB1A00-1234-5678-ABC1-1A001B00CC3D}"),
			ToOwnerName:                 zero.StringFrom("Easy Access to System Information 3"),
			ToOwnerType:                 zero.StringFrom("System"),
			TypeOfData: []*models.CedarExchangeTypeOfDataItem{{
				ID:   zero.StringFrom("{11AB1A00-1234-5678-ABC1-1A001B00CC3D}"),
				Name: zero.StringFrom("Information Resources 2"),
			}},
		},
	},
	"{11AB1A00-1234-5678-ABC1-1A001B00CC4E}": {
		{
			ConnectionFrequency:         []zero.String{zero.StringFrom("Ad Hoc"), zero.StringFrom("As Needed")},
			ContainsBankingData:         true,
			ContainsBeneficiaryAddress:  true,
			ContainsPhi:                 true,
			ContainsPii:                 true,
			ContainsHealthDisparityData: true,
			DataExchangeAgreement:       zero.StringFrom("No"),
			DataFormat:                  zero.StringFrom("TXT"),
			DataFormatOther:             zero.StringFrom(""),
			ExchangeDescription:         zero.StringFrom("Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat."),
			ExchangeEndDate:             zero.TimeFrom(time.Time{}),
			ExchangeID:                  zero.StringFrom("{11AB1A00-1234-5678-ABC1-1A001B00CC4E}"),
			ExchangeName:                zero.StringFrom("IT Project Business Cases"),
			ExchangeRetiredDate:         zero.TimeFrom(time.Time{}),
			ExchangeStartDate:           zero.TimeFrom(time.Time{}),
			ExchangeState:               zero.StringFrom("Paused"),
			ExchangeVersion:             zero.StringFrom("24"),
			ExchangeDirection:           models.ExchangeDirectionReceiver,
			FromOwnerID:                 zero.StringFrom("{11AB1A00-1234-5678-ABC1-1A001B00CC4E}"),
			FromOwnerName:               zero.StringFrom("CMS Enterprise Data Analytics Repository"),
			FromOwnerType:               zero.StringFrom("System"),
			IsBeneficiaryMailingFile:    true,
			NumOfRecords:                zero.StringFrom("< 1000"),
			SharedViaAPI:                true,
			ToOwnerID:                   zero.StringFrom("{11AB1A00-1234-5678-ABC1-1A001B00CC4E}"),
			ToOwnerName:                 zero.StringFrom("Easy Access to System Information"),
			ToOwnerType:                 zero.StringFrom("System"),
			TypeOfData: []*models.CedarExchangeTypeOfDataItem{{
				ID:   zero.StringFrom("{11AB1A00-1234-5678-ABC1-1A001B00CC4E}"),
				Name: zero.StringFrom("Information Resources"),
			}},
		},
		{
			ConnectionFrequency:         []zero.String{zero.StringFrom("Ad Hoc"), zero.StringFrom("As Needed")},
			ContainsBankingData:         false,
			ContainsBeneficiaryAddress:  false,
			ContainsPhi:                 false,
			ContainsPii:                 false,
			ContainsHealthDisparityData: false,
			DataExchangeAgreement:       zero.StringFrom("Yes"),
			DataFormat:                  zero.StringFrom("YAML"),
			DataFormatOther:             zero.StringFrom(""),
			ExchangeDescription:         zero.StringFrom("Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat."),
			ExchangeEndDate:             zero.TimeFrom(time.Time{}),
			ExchangeID:                  zero.StringFrom("{11AB1A00-1234-5678-ABC1-1A001B00CC4E}"),
			ExchangeName:                zero.StringFrom("IT Project Business Cases 2"),
			ExchangeRetiredDate:         zero.TimeFrom(time.Time{}),
			ExchangeStartDate:           zero.TimeFrom(time.Time{}),
			ExchangeState:               zero.StringFrom("Active"),
			ExchangeVersion:             zero.StringFrom("20"),
			ExchangeDirection:           models.ExchangeDirectionSender,
			FromOwnerID:                 zero.StringFrom("{11AB1A00-1234-5678-ABC1-1A001B00CC4E}"),
			FromOwnerName:               zero.StringFrom("CMS Enterprise Data Analytics Repository 2"),
			FromOwnerType:               zero.StringFrom("System"),
			IsBeneficiaryMailingFile:    false,
			NumOfRecords:                zero.StringFrom("< 3000"),
			SharedViaAPI:                false,
			ToOwnerID:                   zero.StringFrom("{11AB1A00-1234-5678-ABC1-1A001B00CC4E}"),
			ToOwnerName:                 zero.StringFrom("Easy Access to System Information 3"),
			ToOwnerType:                 zero.StringFrom("System"),
			TypeOfData: []*models.CedarExchangeTypeOfDataItem{{
				ID:   zero.StringFrom("{11AB1A00-1234-5678-ABC1-1A001B00CC4E}"),
				Name: zero.StringFrom("Information Resources 2"),
			}},
		},
	},
}

// GetExchange returns a mock slice of CedarExchange structs
func GetExchange(cedarSystemID string) []*models.CedarExchange {
	if val, ok := mockExchanges[cedarSystemID]; ok {
		return val
	}

	return []*models.CedarExchange{}
}
