linters-settings:
  gosec:
    # Currently excluding rule G602 due to issue slowing down execution
    # https://github.com/securego/gosec/issues/1010
    # If we ever re-enable this rule, make sure https://github.com/securego/gosec/issues/1005 is also fixed
    excludes:
      - "G602"
  govet:
    check-shadowing: true
    settings:
      printf:
        funcs:
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf
  goimports:
    # put imports beginning with prefix after 3rd-party packages;
    # it's a comma-separated list of prefixes
    local-prefixes: github.com/cmsgov/easi-app
  revive:
    confidence: 0.1 # Default is 0.8. We want to ignore things that have an extremely low confidence level

linters:
  enable:
     - gosec
     - gofmt
     - goimports
     - govet
     - typecheck
     - ineffassign
     - revive
     - staticcheck
     - gosimple #will be deprecated in golangci-lint v2.0 in favor of staticcheck https://github.com/golangci/golangci-lint/issues/357
     - unused #will be deprecated in golangci-lint v2.0 in favor of staticcheck https://github.com/golangci/golangci-lint/issues/357
     - exhaustive
  disable:
    - errcheck #requires patching code
issues:
  exclude-use-default: false
  exclude:
    - "package-comments"

run:
  # timeout for analysis, e.g. 30s, 5m, default is 1m
  deadline: 8m
  concurrency: 1
