---
version: '3.7'
services:
  db:
    ports:
      - 5432:5432
  db_migrate:
    build:
      context: .
      dockerfile: Dockerfile.db_migrations
    image: easi-db-migrate:latest
    volumes:
      - ./migrations:/flyway/sql
  easi:
    build:
      context: .
      dockerfile: Dockerfile
    image: easi-backend:latest
    ports:
      - 8080:8080
  easi_client:
    build:
      context: .
      dockerfile: Dockerfile.client
      args:
        - REACT_APP_APP_ENV=$APP_ENV
        - REACT_APP_API_ADDRESS=http://easi:8080/api/v1
        - REACT_APP_OKTA_CLIENT_ID=$OKTA_CLIENT_ID_DEV
        - REACT_APP_OKTA_DOMAIN=$OKTA_DOMAIN
        - REACT_APP_OKTA_ISSUER=$OKTA_ISSUER
        - REACT_APP_OKTA_REDIRECT_URI=http://localhost:3000/implicit/callback
        - REACT_APP_OKTA_SERVER_ID=$OKTA_SERVER_ID_DEV
    ports:
      - 3000:3000
  cypress:
    volumes:
      - ./cypress/videos:/cypress/videos
      - ./cypress/screenshots:/cypress/screenshots
  lambda:
    image: lambci/lambda:go1.x
    ports:
      - 9001:9001
    environment:
      - DOCKER_LAMBDA_STAY_OPEN=1
      - LICENSE_KEY=
    volumes:
      - ./../easi-infra-modules/lambda/prince/build:/var/task:ro,delegated
