FROM circleci/node:10 AS builder
USER root

WORKDIR /app
COPY . .

ARG REACT_APP_API_ADDRESS
ARG REACT_APP_OKTA_CLIENT_ID
ARG REACT_APP_OKTA_DOMAIN
ARG REACT_APP_OKTA_ISSUER
ARG REACT_APP_OKTA_REDIRECT_URI
ARG REACT_APP_OKTA_SERVER_ID

RUN yarn install
RUN yarn run build

FROM circleci/node:10
USER root

RUN yarn global add serve
WORKDIR /app
COPY --from=builder /app/build .
