---
version: '3.7'
services:
  db_migrate:
    image: '${ECR_REGISTRY}/easi-db-migrate:${GIT_HASH}'
  db_seed:
    build:
      context: .
      dockerfile: Dockerfile.db_seed
    environment:
      - PGHOST=db
      - PGPORT=5432
      - PGDATABASE=postgres
      - PGUSER=postgres
      - PGPASS=mysecretpassword
      - PGSSLMODE=disable
      - DB_MAX_CONNECTIONS=20
  easi:
    image: '${ECR_REGISTRY}/easi-backend:${GIT_HASH}'
    environment:
      - APP_ENV=test
      - EMAIL_TEMPLATE_DIR=/easi/templates
      - SERVER_CERT
      - SERVER_KEY
      - LOCAL_AUTH_ENABLED=true
      - FLAG_SOURCE=FILE
      - FLAGDATA_FILE=/cypress/fixtures/flagdata.json
    volumes:
      - ./cypress:/cypress # Mounted so that the backend container can access the file with LaunchDarkly flag values
  easi_client:
    build:
      context: .
      dockerfile: Dockerfile.client_ci
    environment:
      - CI=true #https://github.com/facebook/create-react-app/issues/8688
    entrypoint: ['serve', '-s', '-l', '3000']
  cypress:
    build:
      context: .
      dockerfile: Dockerfile.cypress
    image: easi-cypress:latest
    environment:
      - OKTA_TEST_USERNAME
      - OKTA_TEST_PASSWORD
      - OKTA_TEST_SECRET
      - REACT_APP_API_ADDRESS=http://easi:8080/api/v1
      - REACT_APP_GRAPHQL_ADDRESS=http://easi:8080/api/graph/query
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_HOST=minio:9000
      - PGHOST=db
      - PGPORT=5432
      - PGDATABASE=postgres
      - PGUSER=postgres
      - PGPASS=mysecretpassword
      - PGSSLMODE=disable
      - DB_MAX_CONNECTIONS=20
      - CYPRESS_MAILCATCHER_API_ADDRESS=http://email:1080
      - CYPRESS_GRT_EMAIL=success@simulator.amazonses.com # should be the same value as GRT_EMAIL in docker-compose.yml
    network_mode: 'service:easi_client'
    depends_on:
      - easi_client
