FROM flyway/flyway:6.3

USER root

RUN apt-get update \
    && apt-get install -y --no-install-recommends netcat \
    && rm -rf /var/lib/apt/lists/*

USER flyway

COPY migrations/ /flyway/sql
COPY scripts/db_entrypoint .

ENTRYPOINT ["db_entrypoint", "migrate"]
