FROM node:10.22.0 AS builder

WORKDIR /app

COPY package.json yarn.lock ./
RUN yarn install

COPY craco.config.js tsconfig.json ./
COPY public ./public
COPY src ./src

ARG REACT_APP_API_ADDRESS
ARG REACT_APP_APP_ENV
ARG REACT_APP_OKTA_CLIENT_ID
ARG REACT_APP_OKTA_DOMAIN
ARG REACT_APP_OKTA_ISSUER
ARG REACT_APP_OKTA_REDIRECT_URI
ARG REACT_APP_OKTA_SERVER_ID

RUN yarn run build

FROM node:10.22.0

RUN yarn global add serve
WORKDIR /app
COPY --from=builder /app/build .
