---
version: '3.7'
services:
  db:
    ports:
      - 5432:5432
  db_migrate:
    build:
      context: .
      dockerfile: Dockerfile.db_migrations
    image: easi-db-migrate:latest
    volumes:
      - ./migrations:/flyway/sql
  easi:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    image: easi-backend:latest
    environment:
      - EMAIL_TEMPLATE_DIR=./pkg/email/templates/
    volumes:
      # - /private/var/folders:/var/folders:cached
      - ${PWD}:${PWD}
    working_dir: ${PWD}
    entrypoint: air
    ports:
      - 8080:8080
  easi_client:
    build:
      target: src
    environment:
        - REACT_APP_APP_ENV=$APP_ENV
        - REACT_APP_API_ADDRESS=http://localhost:8080/api/v1
        - REACT_APP_OKTA_CLIENT_ID=$OKTA_CLIENT_ID_DEV
        - REACT_APP_OKTA_DOMAIN=$OKTA_DOMAIN
        - REACT_APP_OKTA_ISSUER=$OKTA_ISSUER
        - REACT_APP_OKTA_REDIRECT_URI=http://localhost:3000/implicit/callback
        - REACT_APP_OKTA_SERVER_ID=$OKTA_SERVER_ID_DEV
        - CHOKIDAR_USEPOLLING=true
    entrypoint: ['yarn', 'start']
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3001:3000
  cypress:
    volumes:
      - ./cypress/videos:/cypress/videos
      - ./cypress/screenshots:/cypress/screenshots
  lambda:
    image: lambci/lambda:go1.x
    ports:
      - 9001:9001
    environment:
      - DOCKER_LAMBDA_STAY_OPEN=1
      - LICENSE_KEY=
    volumes:
      - ./../easi-infra-modules/lambda/prince/build:/var/task:ro,delegated
