---
version: '3.7'
services:
  db_migrate:
    build:
      context: .
      dockerfile: Dockerfile.db_migrations
    image: easi-db-migrate:latest
    volumes:
      - ./migrations:/flyway/sql
  easi:
    build:
      context: .
      dockerfile: Dockerfile
    image: easi-backend:latest
  cypress:
    volumes:
      - ./cypress/videos:/cypress/videos
      - ./cypress/screenshots:/cypress/screenshots
