ARG TAG=9.10
FROM flyway/flyway:${TAG}

COPY migrations/ /flyway/sql

ENV FLYWAY_CONNECT_RETRIES=10
ENV FLYWAY_CLEAN_DISABLED="true"

ENTRYPOINT ["flyway", "-validateMigrationNaming=true", "migrate"]
