services:
  db_migrate:
    image: '${ECR_REGISTRY}/easi-db-migrate:${GIT_HASH}'
  db_seed:
    build:
      context: .
      dockerfile: Dockerfile.db_seed
    image: db_seed:latest
    environment:
      - PGHOST=db
      - PGPORT=5432
      - PGDATABASE=postgres
      - PGUSER=postgres
      - PGPASS=mysecretpassword
      - PGSSLMODE=disable
      - DB_MAX_CONNECTIONS=20
      - AWS_REGION=us-west-2
      - AWS_S3_FILE_UPLOAD_BUCKET=easi-app-file-uploads
      - MINIO_ADDRESS=http://minio:9004
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
  easi:
    image: '${ECR_REGISTRY}/easi-backend:${GIT_HASH}'
    environment:
      - APP_ENV=test
      - EMAIL_TEMPLATE_DIR=/easi/templates
      - SERVER_CERT
      - SERVER_KEY
      - LOCAL_AUTH_ENABLED=true
      - CEDAR_EMAIL_ADDRESS=fake@cedar.gov
      - FLAG_SOURCE=FILE
      - FLAGDATA_FILE=/cypress/fixtures/flagdata.json
      - MINIO_ADDRESS=http://minio:9004
    volumes:
      - ./cypress:/cypress # Mounted so that the backend container can access the file with LaunchDarkly flag values
  easi_client:
    build:
      context: .
      dockerfile: Dockerfile.client_ci
    image: easi_client:latest
    environment:
      - CI=true #https://github.com/facebook/create-react-app/issues/8688
    entrypoint: ['serve', '-s', '-l', '3000']
  cypress:
    build:
      context: .
      dockerfile: Dockerfile.cypress
    image: easi_cypress:latest
    environment:
      - OKTA_TEST_USERNAME
      - OKTA_TEST_PASSWORD
      - OKTA_TEST_SECRET
      - VITE_API_ADDRESS=http://easi:8080/api/v1
      - MINIO_ADDRESS=minio
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - PGHOST=db
      - PGPORT=5432
      - PGDATABASE=postgres
      - PGUSER=postgres
      - PGPASS=mysecretpassword
      - PGSSLMODE=disable
      - DB_MAX_CONNECTIONS=20
    network_mode: 'service:easi_client'
    depends_on:
      - easi_client
    volumes:
      - ./minio_config.json:/root/.mc/config.json
