FROM node:18.20.4 AS base

WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

FROM base AS modules

COPY package.json yarn.lock ./

RUN yarn install --frozen-lockfile

FROM modules AS build

COPY tsconfig.json .eslintrc vite.config.ts apollo.config.js index.html ./
COPY public ./public
COPY src ./src

ENTRYPOINT [ "yarn", "start" ]
