FROM golang:1.26.2 AS base

WORKDIR /easi/

FROM base AS modules

COPY go.mod go.sum ./
RUN go mod download

FROM modules AS build

COPY cmd ./cmd
COPY pkg ./pkg

FROM cypress/base:20.14.0

# mc - minio client, used for tagging uploaded files
COPY --from=quay.io/minio/mc:latest /usr/bin/mc /mc

COPY package.json yarn.lock /
# RUN npm install -g yarn
RUN yarn install --immutable

COPY cypress /cypress
COPY cypress.config.ts /
COPY tsconfig.json /
COPY src /src
COPY scripts/tag_minio_file /scripts/tag_minio_file

ENTRYPOINT ["/node_modules/.bin/cypress"]
CMD ["run"]
