// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/google/uuid"
)

type AccessibilityRequestEdge struct {
	Cursor string                `json:"cursor"`
	Node   *AccessibilityRequest `json:"node"`
}

type AccessibilityRequestsConnection struct {
	TotalCount int                         `json:"totalCount"`
	Edges      []*AccessibilityRequestEdge `json:"edges"`
}

type CreateAccessibilityRequestInput struct {
	Name string `json:"name"`
}

type CreateAccessibilityRequestPayload struct {
	AccessibilityRequest *AccessibilityRequest `json:"accessibilityRequest"`
	UserErrors           []*UserError          `json:"userErrors"`
}

type System struct {
	IntakeID    *uuid.UUID `json:"intakeId"`
	LifecycleID *string    `json:"lifecycleId"`
	ProjectName *string    `json:"projectName"`
	OwnerName   *string    `json:"ownerName"`
}

type UserError struct {
	Message string   `json:"message"`
	Path    []string `json:"path"`
}
