ALTER TYPE action_type ADD VALUE 'CLOSE_REQUEST' BEFORE 'SUBMIT_INTAKE';
ALTER TYPE action_type ADD VALUE 'REOPEN_REQUEST' BEFORE 'SUBMIT_INTAKE';
ALTER TYPE action_type ADD VALUE 'NOT_GOVERNANCE' BEFORE 'SUBMIT_INTAKE';
ALTER TYPE system_intake_decision_state RENAME VALUE 'NO_GOVERNANCE' TO 'NOT_GOVERNANCE';
