CREATE TYPE DISCUSSION_BOARD_TYPE AS ENUM ('PRIMARY', 'INTERNAL');

ALTER TABLE IF EXISTS system_intake_internal_grb_review_discussion_posts
ADD COLUMN IF NOT EXISTS discussion_board_type DISCUSSION_BOARD_TYPE NOT NULL DEFAULT 'INTERNAL';
