ALTER TYPE system_intake_status ADD VALUE 'NEED_BIZ_CASE';
ALTER TYPE system_intake_status ADD VALUE 'BIZ_CASE_DRAFT';
ALTER TYPE system_intake_status ADD VALUE 'BIZ_CASE_DRAFT_SUBMITTED';
ALTER TYPE system_intake_status ADD VALUE 'BIZ_CASE_CHANGES_NEEDED';
ALTER TYPE system_intake_status ADD VALUE 'BIZ_CASE_FINAL_NEEDED';
ALTER TYPE system_intake_status ADD VALUE 'BIZ_CASE_FINAL_SUBMITTED';
ALTER TYPE system_intake_status ADD VALUE 'NOT_APPROVED';
ALTER TYPE system_intake_status ADD VALUE 'NO_GOVERNANCE';
