---
version: 2
jobs:
  pre_test:
    docker:
      - image: trussworks/circleci-docker-primary:tf12-5ee2cb35bc081dbc91da46afc3904ef0e1c111fb
    steps:
      - checkout
      - restore_cache:
          keys:
            - pre-commit-dot-cache-{{ checksum ".pre-commit-config.yaml" }}
      - restore_cache:
          keys:
            - yarn-deps-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies for pre-commit in yarn (temporary?)
          command: yarn install
      - run:
          name: Run pre-commit checks
          command: pre-commit run --all-files --show-diff-on-failure
      - run:
          name: Run Frontend Tests
          command: yarn test
      - save_cache:
          key: pre-commit-dot-cache-{{ checksum ".pre-commit-config.yaml" }}
          paths:
            - ~/.cache/pre-commit
      - save_cache:
          key: yarn-deps-cache-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

  build_tag_push:
    docker:
      - image: trussworks/circleci-docker-primary:tf12-5ee2cb35bc081dbc91da46afc3904ef0e1c111fb
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build the app in docker, tag, and push to ECR
          command: |
            ./scripts/release

  test:
    docker:
      - image: trussworks/circleci-docker-primary:tf12-5ee2cb35bc081dbc91da46afc3904ef0e1c111fb
    steps:
      - checkout
      - run:
          name: Run easi app tests
          command: |
            ./scripts/build
            ./scripts/testsuite

workflows:
  version: 2
  compile:
    jobs:
      - pre_test
      - test
      - build_tag_push:
          requires:
            - pre_test
            - test
