---
version: 2

references:
  circleci_docker_primary: &circleci_docker_primary trussworks/circleci-docker-primary:822fac1c30f3bb7d5d595bed5d2dc86265c4f2f0
  postgres: &postgres postgres:11.6
  db_migrate: &db_migrate ${AWS_ACCOUNT_ID}.dkr.ecr.us-west-2.amazonaws.com/easi-db-migrate:${CIRCLE_SHA1}
jobs:
  restart_impl_ecs_app_service:
    docker:
      - image: *circleci_docker_primary
        environment:
          AWS_DEFAULT_REGION: us-west-2
          APP_ENV: impl
    steps:
      - checkout
      - run:
          name: Setup custom environment variables
          command: |
            temp_role=$(aws sts assume-role \
                    --role-arn arn:aws:iam::$AWS_ACCOUNT_ID_IMPL:role/circleci \
                    --role-session-name circleci)
            echo "export AWS_ACCESS_KEY_ID=$(jq --raw-output .Credentials.AccessKeyId <<< "$temp_role")" >> $BASH_ENV
            echo "export AWS_SECRET_ACCESS_KEY=$(jq --raw-output .Credentials.SecretAccessKey <<< "$temp_role")" >> $BASH_ENV
            echo "export AWS_SESSION_TOKEN=$(jq --raw-output .Credentials.SessionToken <<< "$temp_role")" >> $BASH_ENV
      - run:
          name: Restart ECS app service
          command: |
            ./scripts/deploy_service "easi-app" "4" ""

  restart_prod_ecs_app_service:
    docker:
      - image: *circleci_docker_primary
        environment:
          AWS_DEFAULT_REGION: us-west-2
          APP_ENV: prod
    steps:
      - checkout
      - run:
          name: Setup custom environment variables
          command: |
            temp_role=$(aws sts assume-role \
                    --role-arn arn:aws:iam::$AWS_ACCOUNT_ID_PROD:role/circleci \
                    --role-session-name circleci)
            echo "export AWS_ACCESS_KEY_ID=$(jq --raw-output .Credentials.AccessKeyId <<< "$temp_role")" >> $BASH_ENV
            echo "export AWS_SECRET_ACCESS_KEY=$(jq --raw-output .Credentials.SecretAccessKey <<< "$temp_role")" >> $BASH_ENV
            echo "export AWS_SESSION_TOKEN=$(jq --raw-output .Credentials.SessionToken <<< "$temp_role")" >> $BASH_ENV
      - run:
          name: Restart ECS app service
          command: |
            ./scripts/deploy_service "easi-app" "4" ""

  build_db_migrate_image:
    docker:
      - image: *circleci_docker_primary
        environment:
          AWS_DEFAULT_REGION: us-west-2
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build the flyway migrations for testing
          command: |
            ./scripts/build_db_image "Dockerfile.db_migrations" "easi-db-migrate"
      - run:
          name: Announce failure
          command: |
            ./scripts/circleci-announce-broken-branch
          when: on_fail

  test:
    docker:
      - image: *circleci_docker_primary
        environment:
          APP_ENV: test
          AWS_REGION: us-west-2 # easi app tests expect AWS_REGION instead of AWS_DEFAULT_REGION
          AWS_SES_SOURCE: "\"EASi Test\" <no-reply-test@info.easi.cms.gov>"
          CLIENT_PROTOCOL: http
          CLIENT_PORT: 3000
          CLIENT_HOSTNAME: localhost:3000
          GRT_EMAIL: success@simulator.amazonses.com
          PGHOST: localhost
          PGPORT: 5432
          PGDATABASE: postgres
          PGUSER: postgres
          PGPASS: easirox
          PGSSLMODE: disable
      - image: *postgres
        environment:
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: easirox
          POSTGRES_USER: postgres
          POSTGRES_HOST_AUTH_METHOD: trust
      - image: *db_migrate
        environment:
          FLYWAY_USER: postgres
          FLYWAY_PASSWORD: easirox
          FLYWAY_URL: jdbc:postgresql://localhost/postgres
    steps:
      - checkout
      - run:
          name: Run easi app tests
          command: |
            ./scripts/build_app
            ./scripts/testsuite
      - run:
          name: Announce failure
          command: |
            ./scripts/circleci-announce-broken-branch
          when: on_fail

  integration_tests:
    docker:
      - image: *circleci_docker_primary
        environment:
          APP_ENV: test
          AWS_DEFAULT_REGION: us-west-2
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - restore_cache:
          keys:
            - yarn-deps-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn install
      - run:
          name: Run Cypress integration tests
          command: |
            ./scripts/run-cypress-test-docker
      - save_cache:
          key: yarn-deps-cache-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - store_artifacts:
          path: cypress/videos
          destination: videos
      - store_artifacts:
          path: cypress/screenshots
          destination: screenshots
      - run:
          name: Announce failure
          command: |
            ./scripts/circleci-announce-broken-branch
          when: on_fail

  lint:
    docker:
      - image: *circleci_docker_primary
    steps:
      - checkout
      - restore_cache:
          keys:
            - pre-commit-dot-cache-{{ checksum ".pre-commit-config.yaml" }}
      - restore_cache:
          keys:
            - yarn-deps-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies for pre-commit in yarn (temporary?)
          command: yarn install
      - run:
          name: Run pre-commit checks
          command: pre-commit run --all-files --show-diff-on-failure
      - run:
          name: Run Frontend Tests
          command: yarn run test
      - run:
          name: Build Frontend Code
          command: yarn run build
      - save_cache:
          key: pre-commit-dot-cache-{{ checksum ".pre-commit-config.yaml" }}
          paths:
            - ~/.cache/pre-commit
      - save_cache:
          key: yarn-deps-cache-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Announce failure
          command: |
            ./scripts/circleci-announce-broken-branch
          when: on_fail

  build_db_clean_image:
    docker:
      - image: *circleci_docker_primary
        environment:
          AWS_DEFAULT_REGION: us-west-2
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build the db cleaner image and push to ECR
          command: |
            ./scripts/build_db_image "Dockerfile.db_clean" "easi-db-clean" "latest"
      - run:
          name: Announce failure
          command: |
            ./scripts/circleci-announce-broken-branch
          when: on_fail

  build_tag_push:
    docker:
      - image: *circleci_docker_primary
        environment:
          AWS_DEFAULT_REGION: us-west-2
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build the app and push to ECR
          command: |
            ./scripts/build_docker_image
      - run:
          name: Check for vulnerability scan findings
          command: |
            ./scripts/check_ecr_findings "easi-backend" "$CIRCLE_SHA1"
      - run:
          name: Announce failure
          command: |
            ./scripts/circleci-announce-broken-branch
          when: on_fail

  deploy_dev:
    docker:
      - image: *circleci_docker_primary
        environment:
          AWS_DEFAULT_REGION: us-west-2
          APP_ENV: dev
    steps:
      - checkout
      - run:
          name: Setup custom environment variables
          command: |
            temp_role=$(aws sts assume-role \
                    --role-arn arn:aws:iam::$AWS_ACCOUNT_ID_DEV:role/circleci \
                    --role-session-name circleci)
            echo "export AWS_ACCESS_KEY_ID=$(jq --raw-output .Credentials.AccessKeyId <<< "$temp_role")" >> $BASH_ENV
            echo "export AWS_SECRET_ACCESS_KEY=$(jq --raw-output .Credentials.SecretAccessKey <<< "$temp_role")" >> $BASH_ENV
            echo "export AWS_SESSION_TOKEN=$(jq --raw-output .Credentials.SessionToken <<< "$temp_role")" >> $BASH_ENV
      - run:
          name: Nuke the database
          command: |
            ./scripts/db_lambda_invoke "easi-app-db-clean-tmp" "2" "easi-app-db-clean"
      - run:
          name: Run migrations
          command: |
            ./scripts/deploy_service "easi-app-db-migrate" "16" "easi-db-migrate"
            ./scripts/db_lambda_invoke "dev-ecs-manager" "16" "easi-app-db-migrate"
      - run:
          name: Deploy ECS service
          command: |
            ./scripts/deploy_service "easi-app" "16" "easi-backend"
            ./scripts/healthcheck
      - run:
          name: Build static assets and release to S3
          command: |
            ./scripts/release_static
      - run:
          name: Announce failure
          command: |
            ./scripts/circleci-announce-broken-branch
          when: on_fail

  deploy_impl:
    docker:
      - image: *circleci_docker_primary
        environment:
          AWS_DEFAULT_REGION: us-west-2
          APP_ENV: impl
    steps:
      - checkout
      - run:
          name: Setup custom environment variables
          command: |
            temp_role=$(aws sts assume-role \
                    --role-arn arn:aws:iam::$AWS_ACCOUNT_ID_IMPL:role/circleci \
                    --role-session-name circleci)
            echo "export AWS_ACCESS_KEY_ID=$(jq --raw-output .Credentials.AccessKeyId <<< "$temp_role")" >> $BASH_ENV
            echo "export AWS_SECRET_ACCESS_KEY=$(jq --raw-output .Credentials.SecretAccessKey <<< "$temp_role")" >> $BASH_ENV
            echo "export AWS_SESSION_TOKEN=$(jq --raw-output .Credentials.SessionToken <<< "$temp_role")" >> $BASH_ENV
      - run:
          name: Backup the database
          command: |
            ./scripts/rds-snapshot-app-db
      - run:
          name: Run migrations
          command: |
            ./scripts/deploy_service "easi-app-db-migrate" "4" "easi-db-migrate"
            ./scripts/db_lambda_invoke "impl-ecs-manager" "4" "easi-app-db-migrate"
      - run:
          name: Deploy ECS service
          command: |
            ./scripts/deploy_service "easi-app" "4" "easi-backend"
            ./scripts/healthcheck
      - run:
          name: Build static assets and release to S3
          command: |
            ./scripts/release_static
      - run:
          name: Announce failure
          command: |
            ./scripts/circleci-announce-broken-branch
          when: on_fail

  deploy_prod:
    docker:
      - image: *circleci_docker_primary
        environment:
          AWS_DEFAULT_REGION: us-west-2
          APP_ENV: prod
    steps:
      - checkout
      - run:
          name: Setup custom environment variables
          command: |
            temp_role=$(aws sts assume-role \
                    --role-arn arn:aws:iam::$AWS_ACCOUNT_ID_PROD:role/circleci \
                    --role-session-name circleci)
            echo "export AWS_ACCESS_KEY_ID=$(jq --raw-output .Credentials.AccessKeyId <<< "$temp_role")" >> $BASH_ENV
            echo "export AWS_SECRET_ACCESS_KEY=$(jq --raw-output .Credentials.SecretAccessKey <<< "$temp_role")" >> $BASH_ENV
            echo "export AWS_SESSION_TOKEN=$(jq --raw-output .Credentials.SessionToken <<< "$temp_role")" >> $BASH_ENV
      - run:
          name: Backup the database
          command: |
            ./scripts/rds-snapshot-app-db
      - run:
          name: Run migrations
          command: |
            ./scripts/deploy_service "easi-app-db-migrate" "4" "easi-db-migrate"
            ./scripts/db_lambda_invoke "prod-ecs-manager" "4" "easi-app-db-migrate"
      - run:
          name: Deploy ECS service
          command: |
            ./scripts/deploy_service "easi-app" "4" "easi-backend"
            ./scripts/healthcheck
      - run:
          name: Build static assets and release to S3
          command: |
            ./scripts/release_static
      - run:
          name: Announce failure
          command: |
            ./scripts/circleci-announce-broken-branch
          when: on_fail

workflows:
  version: 2
  compile:
    jobs:
      - build_db_migrate_image
      - lint
      - test:
          requires:
            - build_db_migrate_image
      - build_tag_push:
          requires:
            - lint
            - test
      - integration_tests:
          requires:
            - build_tag_push
      - hold_dev:
          type: approval
          filters:
            branches:
              ignore:
                - master
      - deploy_dev:
          filters:
            branches:
              ignore:
                - master
          requires:
            - integration_tests
            - hold_dev
      - deploy_impl:
          filters:
            branches:
              only:
                - master
          requires:
            - integration_tests
      - hold_prod:
          type: approval
          requires:
            - deploy_impl
      - deploy_prod:
          requires:
            - hold_prod
  weekly:
    triggers:
      - schedule:
          cron: "0 2 * * 6"
          filters:
            branches:
              only:
                - master
    jobs:
      - build_db_clean_image

  daily:
    triggers:
      - schedule:
          cron: "0 7 * * *"   # 2300 PST, 0200 EST
          filters:
            branches:
              only:
                master
    jobs:
      - restart_impl_ecs_app_service
      - restart_prod_ecs_app_service
