- op: replace
  path: /metadata/labels
  value: 
    fargate: 'true'
- op: replace
  path: /metadata/annotations
  value:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: /api/v1/healthcheck
- op: replace
  path: /spec
  value:
    ingressClassName: alb
    rules:
    - http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: easi-backend
              port:
                number: 8080

# expected output:
#
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   labels:
#     fargate: 'true'
#   annotations:
#     alb.ingress.kubernetes.io/scheme: internet-facing
#     alb.ingress.kubernetes.io/target-type: ip
#     alb.ingress.kubernetes.io/healthcheck-path: /api/v1/healthcheck
#   name: easi-backend-ingress
#   namespace: easi
# spec:
#   ingressClassName: alb
#   rules:
#   - http:
#       paths:
#       - backend:
#           service:
#             name: easi-backend
#             port:
#               number: 8080
#         path: /
#         pathType: Prefix