apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/ingress

patches:

# Patches to update ingress for use with AWS ALB
- path: easi_ingress.yaml
  target:
    name: easi-ingress
- path: email_ingress.yaml
  target:
    name: email-ingress
- path: minio_ingress.yaml
  target:
    name: minio-console-ingress
