export const GOVTEAM_DEV = 'EASI_D_GOVTEAM';
export const GOVTEAM_PROD = 'EASI_P_GOVTEAM';
export const FIVE08TESTER_DEV = 'EASI_D_508TESTER';
export const FIVE08TESTER_PROD = 'EASI_P_508TESTER';
export const FIVE08ADMIN_DEV = 'EASI_D_508ADMIN';
export const FIVE08ADMIN_PROD = 'EASI_P_508ADMIN';

export const JOB_CODES = [
  GOVTEAM_DEV,
  GOVTEAM_PROD,
  FIVE08TESTER_DEV,
  FIVE08TESTER_PROD,
  FIVE08ADMIN_DEV,
  FIVE08ADMIN_PROD
];

export default JOB_CODES;
