export const GOVTEAM_DEV = 'EASI_D_GOVTEAM';
export const GOVTEAM_PROD = 'EASI_P_GOVTEAM';
export const ACCESSIBILITY_TESTER_DEV = 'EASI_D_508TESTER';
export const ACCESSIBILITY_TESTER_PROD = 'EASI_P_508TESTER';
export const ACCESSIBILITY_ADMIN_DEV = 'EASI_D_508ADMIN';
export const ACCESSIBILITY_ADMIN_PROD = 'EASI_P_508ADMIN';

export const JOB_CODES = [
  GOVTEAM_DEV,
  GOVTEAM_PROD,
  ACCESSIBILITY_TESTER_DEV,
  ACCESSIBILITY_TESTER_PROD,
  ACCESSIBILITY_ADMIN_DEV,
  ACCESSIBILITY_ADMIN_PROD
];

export default JOB_CODES;
