export const GET_SYSTEM_INTAKE: string = 'GET_SYSTEM_INTAKE';
export const PUT_SYSTEM_INTAKE: string = 'PUT_SYSTEM_INTAKE';
export const DELETE_SYSTEM_INTAKE: string = 'DELETE_SYSTEM_INTAKE';
export const UPDATE_SYSTEM_INTAKE: string = 'UPDATE_SYSTEM_INTAKE';
