export const FETCH_SYSTEM_INTAKE: string = 'FETCH_SYSTEM_INTAKE';
export const STORE_SYSTEM_INTAKE: string = 'STORE_SYSTEM_INTAKE';
export const DELETE_SYSTEM_INTAKE: string = 'DELETE_SYSTEM_INTAKE';
export const UPDATE_SYSTEM_INTAKE: string = 'UPDATE_SYSTEM_INTAKE';
