apiVersion: v1
kind: ConfigMap
metadata:
  name: cedarproxy-configmap
  namespace: easi
data:
  CEDAR_API_URL: webmethods-apigw.cedarimpl.cms.gov
  CEDAR_CACHE_EXPIRE_TIME: "7d"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cedarproxy
  namespace: easi
spec:
  selector:
    matchLabels:
      app: cedarproxy
  template:
    metadata:
      labels:
        app: cedarproxy
    spec:
      containers:
      - name: cedarproxy
        image: cedarproxy:latest
        imagePullPolicy: Never
        envFrom:
          - configMapRef:
              name: cedarproxy-configmap
        resources: {}
        ports:
        - containerPort: 8001

---

apiVersion: v1
kind: Service
metadata:
  name: cedarproxy
  namespace: easi
spec:
  selector:
    app: cedarproxy
  ports:
  - port: 8001
    targetPort: 8001
