apiVersion: v1
kind: ConfigMap
metadata:
  name: db-configmap
  namespace: easi
data:
  POSTGRES_PASSWORD: mysecretpassword

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: easi
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  strategy: {}
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - args:
            - postgres
            - -c
            - log_statement=all
            - -c
            - max_connections=25
          envFrom:
            - configMapRef:
                name: db-configmap        
          image: postgres:14.11
          name: db
          ports:
            - containerPort: 5432
              protocol: TCP
          resources: {}
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  namespace: easi
  name: db
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: db

---

apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: db-migrate
  name: db-migrate
  namespace: easi
spec:
  template:
    metadata:
      labels:
        app: db-migrate
    spec:
      containers:
        - env:
            - name: FLYWAY_PASSWORD
              value: mysecretpassword
            - name: FLYWAY_PLACEHOLDERS_APP_USER_PASSWORD
              value: supersecretapp
            - name: FLYWAY_URL
              value: jdbc:postgresql://db/postgres
            - name: FLYWAY_USER
              value: postgres
          image: db-migrate:latest
          imagePullPolicy: Never
          name: db-migrate
          resources: {}
      restartPolicy: Never
  backoffLimit: 4
  completions: 1
  parallelism: 1
