apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: email
  name: email
  namespace: easi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: email
  template:
    metadata:
      labels:
        app: email
    spec:
      containers:
        - image: dockage/mailcatcher:latest
          name: email
          ports:
            - containerPort: 1025
              protocol: TCP
            - containerPort: 1080
              protocol: TCP
          resources: {}
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: email
  namespace: easi
spec:
  ports:
    - name: "smtp"
      port: 1025
      targetPort: 1025
    - name: "http"
      port: 1080
      targetPort: 1080
  selector:
    app: email

--- 

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: email-ingress
  namespace: easi
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - host: email.localdev.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: email
                port:
                  number: 1080
