apiVersion: v1
kind: Service
metadata:
  namespace: easi
  name: minio
spec:
  ports:
    - name: "9004"
      port: 9004
      targetPort: 9004
    - name: "console"
      port: 9001
      targetPort: 9001
  selector:
    app: minio
