# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: minio-server
#   namespace: easi
# data:

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: easi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - command: ["minio", "server", "/data", "--console-address"]
          args: [':9001', '--address', ':9004']
          image: minio/minio:latest
          name: minio
          ports:
            - containerPort: 9004
              hostPort: 9004
              protocol: TCP
            - containerPort: 9001
              hostPort: 9001
          resources: {}
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  namespace: easi
  name: minio
spec:
  ports:
    - name: "9004"
      port: 9004
      targetPort: 9004
    - name: "console"
      port: 9001
      targetPort: 9001
  selector:
    app: minio
  
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-console-ingress
  namespace: easi
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
  - host: minio.localdev.me
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: minio
            port: 
              number: 9001

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: minio-mc-config
  namespace: easi
data:
  config.json: |
    {
      "version": "10",
      "aliases": {
        "local": {
          "url": "http://minio:9004",
          "accessKey": "minioadmin",
          "secretKey": "minioadmin",
          "api": "S3v4",
          "path": "auto"
        }
      }
    }

---

apiVersion: batch/v1
kind: Job
metadata:
  name: minio-mc
  namespace: easi
  labels:
    app: minio-mc
spec:
  template:
    metadata:
      labels:
        app: minio-mc
    spec:
      volumes:
        - name: minio-mc-config
          configMap:
            name: minio-mc-config
      containers:
      - name: minio-mc
        image: minio/mc:latest
        volumeMounts:
          - mountPath: /root/.mc/config.json
            name: minio-mc-config
            subPath: config.json
        command: ["/bin/sh","-c"]
        args:
        - /usr/bin/mc mb local/easi-app-file-uploads/;
          /usr/bin/mc anonymous set public local/easi-app-file-uploads
        resources: {}
      restartPolicy: Never
  backoffLimit: 4
  completions: 1
  parallelism: 1
  ttlSecondsAfterFinished: 1000
