package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"
	"errors"

	"github.com/google/uuid"

	"github.com/cms-enterprise/easi-app/pkg/appcontext"
	"github.com/cms-enterprise/easi-app/pkg/apperrors"
	cedarcore "github.com/cms-enterprise/easi-app/pkg/cedar/core"
	"github.com/cms-enterprise/easi-app/pkg/graph/generated"
	"github.com/cms-enterprise/easi-app/pkg/models"
)

// BusinessOwnerRoles is the resolver for the businessOwnerRoles field.
func (r *cedarSystemResolver) BusinessOwnerRoles(ctx context.Context, obj *models.CedarSystem) ([]*models.CedarRole, error) {
	cedarRoles, err := r.cedarCoreClient.GetBusinessOwnerRolesBySystem(ctx, obj.ID)
	if err != nil {
		return nil, err
	}
	return cedarRoles, nil
}

// IsBookmarked is the resolver for the isBookmarked field.
func (r *cedarSystemResolver) IsBookmarked(ctx context.Context, obj *models.CedarSystem) (bool, error) {
	return GetCedarSystemIsBookmarked(ctx, obj.ID)
}

// ViewerCanAccessProfile is the resolver for the viewerCanAccessProfile field.
func (r *cedarSystemResolver) ViewerCanAccessProfile(ctx context.Context, obj *models.CedarSystem) (bool, error) {
	capabilities, err := GetCedarSystemViewerCapabilities(ctx, obj.ID)
	if err != nil {
		return false, err
	}

	return capabilities.ViewerCanAccessProfile, nil
}

// ViewerCanAccessWorkspace is the resolver for the viewerCanAccessWorkspace field.
func (r *cedarSystemResolver) ViewerCanAccessWorkspace(ctx context.Context, obj *models.CedarSystem) (bool, error) {
	if obj.WorkspaceAccessPreAuthorized {
		return true, nil
	}

	capabilities, err := GetCedarSystemViewerCapabilities(ctx, obj.ID)
	if err != nil {
		return false, err
	}

	return capabilities.ViewerCanAccessWorkspace, nil
}

// LinkedTrbRequests is the resolver for the linkedTrbRequests field.
func (r *cedarSystemResolver) LinkedTrbRequests(ctx context.Context, obj *models.CedarSystem, state models.TRBRequestState) ([]*models.TRBRequest, error) {
	trbRequests, err := CedarSystemLinkedTRBRequests(ctx, obj.ID, state)
	if err != nil {
		return nil, err
	}

	if obj.WorkspaceAccessPreAuthorized {
		return trbRequests, nil
	}

	err = authorizeUserCanAccessCEDARSystemWorkspace(ctx, r.cedarCoreClient, obj.ID)
	if err == nil {
		return trbRequests, nil
	}

	var unauthorizedErr *apperrors.UnauthorizedError
	if !errors.As(err, &unauthorizedErr) {
		return nil, err
	}

	return filterVisibleTRBRequests(ctx, trbRequests)
}

// LinkedSystemIntakes is the resolver for the linkedSystemIntakes field.
func (r *cedarSystemResolver) LinkedSystemIntakes(ctx context.Context, obj *models.CedarSystem, state models.SystemIntakeState) ([]*models.SystemIntake, error) {
	intakes, err := CedarSystemLinkedSystemIntakes(ctx, obj.ID, state)
	if err != nil {
		return nil, err
	}

	if obj.WorkspaceAccessPreAuthorized {
		return intakes, nil
	}

	err = authorizeUserCanAccessCEDARSystemWorkspace(ctx, r.cedarCoreClient, obj.ID)
	if err == nil {
		return intakes, nil
	}

	var unauthorizedErr *apperrors.UnauthorizedError
	if !errors.As(err, &unauthorizedErr) {
		return nil, err
	}

	return filterVisibleSystemIntakes(ctx, r.store, intakes)
}

// SystemMaintainerInformation is the resolver for the systemMaintainerInformation field.
func (r *cedarSystemDetailsResolver) SystemMaintainerInformation(ctx context.Context, obj *models.CedarSystemDetails) (*models.CedarSystemMaintainerInformation, error) {
	if obj.SystemMaintainerInformation == nil {
		return nil, nil
	}
	return &models.CedarSystemMaintainerInformation{
		AdHocAgileDeploymentFrequency:         obj.SystemMaintainerInformation.AdHocAgileDeploymentFrequency.Ptr(),
		AgileUsed:                             &obj.SystemMaintainerInformation.AgileUsed,
		AuthoritativeDatasource:               obj.SystemMaintainerInformation.AuthoritativeDatasource.Ptr(),
		BusinessArtifactsOnDemand:             &obj.SystemMaintainerInformation.BusinessArtifactsOnDemand,
		DataAtRestEncryptionKeyManagement:     obj.SystemMaintainerInformation.DataAtRestEncryptionKeyManagement.Ptr(),
		DeploymentFrequency:                   obj.SystemMaintainerInformation.DeploymentFrequency.Ptr(),
		DevCompletionPercent:                  obj.SystemMaintainerInformation.DevCompletionPercent.Ptr(),
		DevWorkDescription:                    obj.SystemMaintainerInformation.DevWorkDescription.Ptr(),
		EcapParticipation:                     &obj.SystemMaintainerInformation.EcapParticipation,
		FrontendAccessType:                    obj.SystemMaintainerInformation.FrontendAccessType.Ptr(),
		HardCodedIPAddress:                    &obj.SystemMaintainerInformation.HardCodedIPAddress,
		IP6EnabledAssetPercent:                obj.SystemMaintainerInformation.IP6EnabledAssetPercent.Ptr(),
		IP6TransitionPlan:                     obj.SystemMaintainerInformation.IP6TransitionPlan.Ptr(),
		IPEnabledAssetCount:                   &obj.SystemMaintainerInformation.IPEnabledAssetCount,
		LegalHoldCaseName:                     obj.SystemMaintainerInformation.LegalHoldCaseName.Ptr(),
		LocallyStoredUserInformation:          &obj.SystemMaintainerInformation.LocallyStoredUserInformation,
		MajorRefreshDate:                      obj.SystemMaintainerInformation.MajorRefreshDate.Ptr(),
		MultifactorAuthenticationMethod:       models.StringsFromZeroStrs(obj.SystemMaintainerInformation.MultifactorAuthenticationMethod),
		MultifactorAuthenticationMethodOther:  obj.SystemMaintainerInformation.MultifactorAuthenticationMethodOther.Ptr(),
		NetAccessibility:                      obj.SystemMaintainerInformation.NetAccessibility.Ptr(),
		NetworkTrafficEncryptionKeyManagement: obj.SystemMaintainerInformation.NetworkTrafficEncryptionKeyManagement.Ptr(),
		NoMajorRefresh:                        &obj.SystemMaintainerInformation.NoMajorRefresh,
		NoPersistentRecordsFlag:               &obj.SystemMaintainerInformation.NoPersistentRecordsFlag,
		NoPlannedMajorRefresh:                 &obj.SystemMaintainerInformation.NoPlannedMajorRefresh,
		OmDocumentationOnDemand:               &obj.SystemMaintainerInformation.OmDocumentationOnDemand,
		PlansToRetireReplace:                  obj.SystemMaintainerInformation.PlansToRetireReplace.Ptr(),
		QuarterToRetireReplace:                obj.SystemMaintainerInformation.QuarterToRetireReplace.Ptr(),
		RecordsManagementBucket:               models.StringsFromZeroStrs(obj.SystemMaintainerInformation.RecordsManagementBucket),
		RecordsManagementDisposalLocation:     obj.SystemMaintainerInformation.RecordsManagementDisposalLocation.Ptr(),
		RecordsManagementDisposalPlan:         obj.SystemMaintainerInformation.RecordsManagementDisposalPlan.Ptr(),
		RecordsUnderLegalHold:                 &obj.SystemMaintainerInformation.RecordsUnderLegalHold,
		SourceCodeOnDemand:                    &obj.SystemMaintainerInformation.SourceCodeOnDemand,
		SystemCustomization:                   obj.SystemMaintainerInformation.SystemCustomization.Ptr(),
		SystemDataLocation:                    models.StringsFromZeroStrs(obj.SystemMaintainerInformation.SystemDataLocation),
		SystemDataLocationNotes:               obj.SystemMaintainerInformation.SystemDataLocationNotes.Ptr(),
		SystemDesignOnDemand:                  &obj.SystemMaintainerInformation.SystemDesignOnDemand,
		SystemProductionDate:                  obj.SystemMaintainerInformation.SystemProductionDate.Ptr(),
		SystemRequirementsOnDemand:            &obj.SystemMaintainerInformation.SystemRequirementsOnDemand,
		TestPlanOnDemand:                      &obj.SystemMaintainerInformation.TestPlanOnDemand,
		TestReportsOnDemand:                   &obj.SystemMaintainerInformation.TestReportsOnDemand,
		TestScriptsOnDemand:                   &obj.SystemMaintainerInformation.TestScriptsOnDemand,
		YearToRetireReplace:                   obj.SystemMaintainerInformation.YearToRetireReplace.Ptr(),
	}, nil
}

// BusinessOwnerInformation is the resolver for the businessOwnerInformation field.
func (r *cedarSystemDetailsResolver) BusinessOwnerInformation(ctx context.Context, obj *models.CedarSystemDetails) (*models.CedarBusinessOwnerInformation, error) {
	if obj.BusinessOwnerInformation == nil {
		return nil, nil
	}
	return &models.CedarBusinessOwnerInformation{
		BeneficiaryAddressPurpose:      models.StringsFromZeroStrs(obj.BusinessOwnerInformation.BeneficiaryAddressPurpose),
		BeneficiaryAddressPurposeOther: obj.BusinessOwnerInformation.BeneficiaryAddressPurposeOther.Ptr(),
		BeneficiaryAddressSource:       models.StringsFromZeroStrs(obj.BusinessOwnerInformation.BeneficiaryAddressSource),
		BeneficiaryAddressSourceOther:  obj.BusinessOwnerInformation.BeneficiaryAddressSourceOther.Ptr(),
		BeneficiaryInformation:         models.StringsFromZeroStrs(obj.BusinessOwnerInformation.BeneficiaryInformation),
		CostPerYear:                    obj.BusinessOwnerInformation.CostPerYear.Ptr(),
		EditBeneficiaryInformation:     &obj.BusinessOwnerInformation.EditBeneficiaryInformation,
		IsCmsOwned:                     &obj.BusinessOwnerInformation.IsCmsOwned,
		Nr508UserInterface:             obj.BusinessOwnerInformation.Nr508UserInterface.Ptr(),
		NumberOfContractorFte:          obj.BusinessOwnerInformation.NumberOfContractorFte.Ptr(),
		NumberOfFederalFte:             obj.BusinessOwnerInformation.NumberOfFederalFte.Ptr(),
		NumberOfSupportedUsersPerMonth: obj.BusinessOwnerInformation.NumberOfSupportedUsersPerMonth.Ptr(),
		StoresBankingData:              &obj.BusinessOwnerInformation.StoresBankingData,
		StoresBeneficiaryAddress:       &obj.BusinessOwnerInformation.StoresBeneficiaryAddress,
	}, nil
}

// IsBookmarked is the resolver for the isBookmarked field.
func (r *cedarSystemWorkspaceSystemResolver) IsBookmarked(ctx context.Context, obj *models.CedarSystemWorkspaceSystem) (bool, error) {
	return GetCedarSystemIsBookmarked(ctx, obj.ID)
}

// ViewerCanAccessProfile is the resolver for the viewerCanAccessProfile field.
func (r *cedarSystemWorkspaceSystemResolver) ViewerCanAccessProfile(ctx context.Context, obj *models.CedarSystemWorkspaceSystem) (bool, error) {
	capabilities, err := GetCedarSystemViewerCapabilities(ctx, obj.ID)
	if err != nil {
		return false, err
	}

	return capabilities.ViewerCanAccessProfile, nil
}

// LinkedTrbRequests is the resolver for the linkedTrbRequests field.
func (r *cedarSystemWorkspaceSystemResolver) LinkedTrbRequests(ctx context.Context, obj *models.CedarSystemWorkspaceSystem, state models.TRBRequestState) ([]*models.TRBRequest, error) {
	trbRequests, err := CedarSystemLinkedTRBRequests(ctx, obj.ID, state)
	if err != nil {
		return nil, err
	}

	err = authorizeUserCanAccessCEDARSystemWorkspace(ctx, r.cedarCoreClient, obj.ID)
	if err == nil {
		return trbRequests, nil
	}

	var unauthorizedErr *apperrors.UnauthorizedError
	if !errors.As(err, &unauthorizedErr) {
		return nil, err
	}

	return filterVisibleTRBRequests(ctx, trbRequests)
}

// LinkedSystemIntakes is the resolver for the linkedSystemIntakes field.
func (r *cedarSystemWorkspaceSystemResolver) LinkedSystemIntakes(ctx context.Context, obj *models.CedarSystemWorkspaceSystem, state models.SystemIntakeState) ([]*models.SystemIntake, error) {
	intakes, err := CedarSystemLinkedSystemIntakes(ctx, obj.ID, state)
	if err != nil {
		return nil, err
	}

	err = authorizeUserCanAccessCEDARSystemWorkspace(ctx, r.cedarCoreClient, obj.ID)
	if err == nil {
		return intakes, nil
	}

	var unauthorizedErr *apperrors.UnauthorizedError
	if !errors.As(err, &unauthorizedErr) {
		return nil, err
	}

	return filterVisibleSystemIntakes(ctx, r.store, intakes)
}

// CedarSystem is the resolver for the cedarSystem field.
func (r *queryResolver) CedarSystem(ctx context.Context, cedarSystemID uuid.UUID) (*models.CedarSystem, error) {
	return GetCedarSystem(ctx, r.cedarCoreClient, cedarSystemID)
}

// CedarSystems is the resolver for the cedarSystems field.
func (r *queryResolver) CedarSystems(ctx context.Context) ([]*models.CedarSystem, error) {
	return GetCedarSystems(ctx, r.cedarCoreClient)
}

// MyCedarSystems is the resolver for the myCedarSystems field.
func (r *queryResolver) MyCedarSystems(ctx context.Context) ([]*models.CedarSystem, error) {
	requesterEUAID := appcontext.Principal(ctx).ID()
	systems, err := r.cedarCoreClient.GetSystemSummary(ctx, cedarcore.SystemSummaryOpts.WithEuaIDFilter(requesterEUAID))
	if err != nil {
		return nil, err
	}

	for _, system := range systems {
		if system != nil {
			system.WorkspaceAccessPreAuthorized = true
		}
	}

	return systems, nil
}

// CedarSystemWorkspace is the resolver for the cedarSystemWorkspace field.
func (r *queryResolver) CedarSystemWorkspace(ctx context.Context, cedarSystemID uuid.UUID) (*models.CedarSystemWorkspace, error) {
	return GetCedarSystemWorkspace(ctx, r.cedarCoreClient, cedarSystemID)
}

// CedarSystemDetails is the resolver for the cedarSystemDetails field.
func (r *queryResolver) CedarSystemDetails(ctx context.Context, cedarSystemID uuid.UUID) (*models.CedarSystemDetails, error) {
	return GetCedarSystemDetails(ctx, r.cedarCoreClient, cedarSystemID)
}

// CedarSystem returns generated.CedarSystemResolver implementation.
func (r *Resolver) CedarSystem() generated.CedarSystemResolver { return &cedarSystemResolver{r} }

// CedarSystemDetails returns generated.CedarSystemDetailsResolver implementation.
func (r *Resolver) CedarSystemDetails() generated.CedarSystemDetailsResolver {
	return &cedarSystemDetailsResolver{r}
}

// CedarSystemWorkspaceSystem returns generated.CedarSystemWorkspaceSystemResolver implementation.
func (r *Resolver) CedarSystemWorkspaceSystem() generated.CedarSystemWorkspaceSystemResolver {
	return &cedarSystemWorkspaceSystemResolver{r}
}

type cedarSystemResolver struct{ *Resolver }
type cedarSystemDetailsResolver struct{ *Resolver }
type cedarSystemWorkspaceSystemResolver struct{ *Resolver }
