package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"
	"fmt"

	"github.com/google/uuid"

	"github.com/cms-enterprise/easi-app/pkg/models"
)

// ReviewRequestedEditField is the resolver for the reviewRequestedEditField field.
func (r *mutationResolver) ReviewRequestedEditField(ctx context.Context, requestedEditFieldID uuid.UUID, outcome models.RequestedEditFieldOutcome) (*models.RequestedEditField, error) {
	panic(fmt.Errorf("not implemented: ReviewRequestedEditField - reviewRequestedEditField"))
}
