export type Flags = {
  atoProcessList: boolean;
  downgradeGovTeam: boolean;
  downgradeTrbAdmin: boolean;
  systemProfileHiddenFields: boolean;
  systemWorkspace: boolean;
  systemWorkspaceRequestsCard: boolean;
  systemWorkspaceTeam: boolean;
  grbReviewTab: boolean;
  powerPlatformEnabled: boolean;
  showAtoColumn: boolean;
  serviceAlertEnabled: boolean;
  editableSystemProfile: boolean;
  systemProfileBusinessInformation: boolean;
  systemProfileImplementationDetails: boolean;
  systemProfileData: boolean;
  systemProfileToolsAndSoftware: boolean;
  systemProfileSubSystems: boolean;
  systemProfileTeam: boolean;
  systemProfileContracts: boolean;
  systemProfileFundingAndBudget: boolean;
  systemProfileAtoAndSecurity: boolean;
};
