apiVersion: v1
kind: ConfigMap
metadata:
  name: easi-backend-configmap
  namespace: easi
data:
  CLIENT_DOMAIN: ${EASI_INGRESS}
  CLIENT_HOSTNAME: ${EASI_INGRESS}:80
  CLIENT_ADDRESS: http://${EASI_INGRESS}
  EMAIL_TEMPLATE_DIR: /easi/templates
