apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/easi

patches:
# Patches to remove cedarproxy resources in EKS VPC
- path: ignore_cedarproxy_configmap.yaml
- path: ignore_cedarproxy_deployment.yaml
- path: ignore_cedarproxy_service.yaml

# Patches for configmap changes
- path: easi-backend_configmap.yaml
  target:
    name: easi-backend-configmap
- path: easi-frontend_configmap.yaml
  target:
    name: easi-frontend-configmap

# Patches for deployment changes
- path: easi-backend_deployment.yaml
  target:
    name: easi-backend
    kind: Deployment
- path: easi-frontend_deployment.yaml
  target:
    name: easi-frontend
    kind: Deployment
- path: minio_deployment.yaml
  target:
    name: minio
    kind: Deployment
- path: db-migrate_job.yaml
  target:
    name: db-migrate
    kind: Job

labels:
- includeSelectors: true
  pairs:
    fargate: "true"
