import i18next from 'i18next';

import cmsDivisionsAndOffices from 'constants/enums/cmsDivisionsAndOffices';
import {
  // closedIntakeStatusesV1,
  // openIntakeStatusesV1,
  RequestType
} from 'types/systemIntake';

// NOTE: these utility functions take strings rather than more restricted types so they can operate on values coming from GraphQL queries,
// which are typed according to the autogenerated types in src/types/graphql-global-types.ts
// To improve this, we could make the status parameter use the GraphQL SystemIntakeStatus type, which would closely couple these functions to the GraphQL API
// or we could add a translation layer between the GraphQL types and our domain types in src/types/systemIntake.ts.

/**
 * Checks whenther an intake is closed
 * @param status - the intake's status
 */
// export const isIntakeClosed = (status: string) => {
//   return closedIntakeStatusesV1.includes(status);
// };

/**
 * Checks whenther an intake is open
 * @param status - the intake's status
 */
// export const isIntakeOpen = (status: string) => {
//   return openIntakeStatusesV1.includes(status);
// };

/**
 * Translate the API enum to a human readable string
 */
export const translateRequestType = (requestType: RequestType) => {
  switch (requestType) {
    case 'NEW':
      return i18next.t('intake:requestType.new');
    case 'RECOMPETE':
      return i18next.t('intake:requestType.recompete');
    case 'MAJOR_CHANGES':
      return i18next.t('intake:requestType.majorChanges');
    case 'SHUTDOWN':
      return i18next.t('intake:requestType.shutdown');
    default:
      return '';
  }
};

/**
 * Get the acronym representation of the component name
 * @param componentToTranslate - component name string that needs to be converted to an acronym
 */
export const getAcronymForComponent = (componentToTranslate: string) => {
  const component = cmsDivisionsAndOffices.find(
    c => c.name === componentToTranslate
  );

  // TODO: what do we return if not found? (should be impossible)
  return component ? component.acronym : 'Other';
};
