import i18next from 'i18next';

import cmsDivisionsAndOffices from 'constants/enums/cmsDivisionsAndOffices';
import { RequestType } from 'types/systemIntake';

// NOTE: these utility functions take strings rather than more restricted types so they can operate on values coming from GraphQL queries,
// which are typed according to the autogenerated types in src/types/graphql-global-types.ts

/**
 * Translate the API enum to a human readable string
 */
export const translateRequestType = (requestType: RequestType) => {
  switch (requestType) {
    case 'NEW':
      return i18next.t('intake:requestType.new');
    case 'RECOMPETE':
      return i18next.t('intake:requestType.recompete');
    case 'MAJOR_CHANGES':
      return i18next.t('intake:requestType.majorChanges');
    case 'SHUTDOWN':
      return i18next.t('intake:requestType.shutdown');
    default:
      return '';
  }
};

/**
 * Get the acronym representation of the component name
 * @param componentToTranslate - component name string that needs to be converted to an acronym
 */
export const getAcronymForComponent = (componentToTranslate: string) => {
  const component = cmsDivisionsAndOffices.find(
    c => c.name === componentToTranslate
  );

  // TODO: what do we return if not found? (should be impossible)
  return component ? component.acronym : 'Other';
};
