#!/usr/bin/env bash
#
# for periodically rebuilding the db cleaner image
#

builddir="$(git rev-parse --show-toplevel)"
scriptdir="$builddir/scripts/"

ecr_db_clean="${AWS_ACCOUNT_ID}.dkr.ecr.us-west-2.amazonaws.com/easi-db-clean"

# log in to ECR
if bash +x -o nounset -c "$(aws ecr get-login --no-include-email --region "us-west-2" --registry-ids "${AWS_ACCOUNT_ID}")" ; then
  if (set -x ; docker build --quiet --no-cache --tag "easi-db-clean" "$builddir" --file Dockerfile.db_clean) ; then
    "$scriptdir"/tag_and_push "easi-db-clean:latest" "${ecr_db_clean}" "latest"
  else
    exit
  fi
else
  exit
fi
