#!/usr/bin/env bash
#
# build `easi` in docker and push to ECR
#

builddir="$(git rev-parse --show-toplevel)"
scriptdir="$builddir/scripts/"

ecr_backend="${AWS_ACCOUNT_ID}.dkr.ecr.us-west-2.amazonaws.com/easi-backend"

APPLICATION_VERSION="${CIRCLE_SHA1:-"$(git rev-parse HEAD)"}"
APPLICATION_DATETIME="$(date --rfc-3339='seconds' --utc)"
APPLICATION_TS="$(date --date="$APPLICATION_DATETIME" '+%s')"

# log in to ECR
if bash +x -o nounset -c "$(aws ecr get-login --no-include-email --region "us-west-2" --registry-ids "${AWS_ACCOUNT_ID}")" ; then
  # build & tag the app image, then push to ECR
  if (set -x ; docker build --quiet --build-arg ARG_APPLICATION_VERSION="$APPLICATION_VERSION" --build-arg ARG_APPLICATION_DATETIME="$APPLICATION_DATETIME" --build-arg ARG_APPLICATION_TS="$APPLICATION_TS" --no-cache --tag "easi" "$builddir") ; then
    "$scriptdir"/tag_and_push "easi" "${ecr_backend}" "${APPLICATION_VERSION}"
  else
    exit
  fi
else
  exit
fi
