#!/usr/bin/env bash

set -eu -o pipefail

payload="{\"repository\": \"$1\", \"imageTag\": \"$2\"}"
aws lambda invoke --function-name ecr-scan-findings --payload "$payload" scan_response.json
totalFindings="$(jq -r < scan_response.json | jq .totalFindings)"
if [[ "$totalFindings" != 0 ]]; then
  echo "Scan found $totalFindings findings!"
  exit 1
else
  echo "Scan found no findings"
fi
