#!/usr/bin/env bash
set -euo pipefail

#####
## Only alert on master branch
#####
[[ $CIRCLE_BRANCH = master ]] || exit 0

NOW=$(date '+%s')

pretext="CircleCI $CIRCLE_BRANCH branch failure!"
title="CircleCI build #$CIRCLE_BUILD_NUM failed on job $CIRCLE_JOB"
message="The $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME $CIRCLE_BRANCH branch broke on job $CIRCLE_JOB! Contact $CIRCLE_USERNAME for more information."

#####
## Announce in Slack channel
#####
# 'color' can be any hex code or the key words 'good', 'warning', or 'danger'
color="warning"
if [[ $CIRCLE_JOB = *"deploy"* ]]; then
  color="danger"
fi

slack_payload=$(
cat <<EOM
{
    "channel": "#oit-easi-alerts",
    "attachments": [
        {
            "fallback": "$message $CIRCLE_BUILD_URL",
            "color": "$color",
            "pretext": "$pretext",
            "author_name": "$CIRCLE_USERNAME",
            "title": "$title",
            "title_link": "$CIRCLE_BUILD_URL",
            "text": "$message",
            "ts": $NOW
        }
    ]
}
EOM
)

echo
echo "Slack Payload:"
echo "$slack_payload"
echo

curl -X POST --data-urlencode payload="$slack_payload" "$SLACK_WEBHOOK_URL"
