#!/usr/bin/env sh
#

command="$1"
timeout=10
hostname=localhost
port=5432

echo "Waiting for port $port to open on $hostname"

until nc -z "$hostname" "$port" ; do
  i=$((i+1))
  if [ "$i" -gt "$timeout" ] ; then
    echo "Gave up waiting for port $port to open on host $hostname. Connectivity may fail"
    break
  fi
  sleep 1
done

echo ""
(set -x ; flyway "$command")
