#!/usr/bin/env bash
# shellcheck disable=SC2016

original_schema_file="pkg/cedar/intake/cedar_intake.yml"
output_schema_file="pkg/cedar/intake/system_intake_schema.json"

if [ ! -f "$original_schema_file" ]
then
  echo "Schema file not found" 1>&2
  exit 1
fi

if ! command -v yq &> /dev/null
then
    echo "yq could not be found."
    echo "Install yq from https://github.com/mikefarah/yq/#install"
    exit 2
fi

yq_commands=(
    'with_entries(select(.key | test("definitions")))' # use only the "definitions" entry
  '| .definitions' # pull out values under "definitions"
  '| with_entries(select(.key | test("EASIIntake")))' # use only the definitions.EASIIntake entry
  '| {"definitions": .}' # put the EASIIntake value back under the key "definitions"
  '| .$schema = "http://json-schema.org/draft-04/schema#"' # add the "$schema" entry
  '| .$ref = "#/definitions/EASIIntake"' # add the "$ref" entry
  '| sort_keys(..)' # sort entries by key names, alphabetically
)

yq_expr=""
for yq_command in "${yq_commands[@]}"; do
  yq_expr+=" $yq_command"
done

yq eval "$yq_expr" --output-format=json "$original_schema_file" > "$output_schema_file"
