#!/usr/bin/env bash

# Run GraphQL generation for Go files
go generate ./... || exit

# If in CI environment, install goimports and specify absolute path to the binary
if [[ -n ${CI-} ]]; then
  GO111MODULE=off go get golang.org/x/tools/cmd/goimports || exit
  "$(go env GOPATH)"/bin/goimports -w -local github.com/cmsgov/easi-app pkg/graph/schema.resolvers.go || exit
else
  goimports -w -local github.com/cmsgov/easi-app pkg/graph/schema.resolvers.go || exit
fi

# Run GraphQL generation for Typescript files
yarn generate

# Generate JSON Schema for CEDAR System Intake
scripts/gen_intake_schema
