#!/usr/bin/env bash

# Run GraphQL generation for Go files
go generate ./... || exit

# If in CirleCI environment, install goimports and specify absolute path to the binary
if [[ -n ${CIRCLECI-} ]]; then
  GO111MODULE=off go get golang.org/x/tools/cmd/goimports || exit
  "$(go env GOPATH)"/bin/goimports -w -local github.com/cmsgov/easi-app pkg/graph/schema.resolvers.go || exit
else
  goimports -w -local github.com/cmsgov/easi-app pkg/graph/schema.resolvers.go || exit
fi

# Run GraphQL generation for Typescript files
yarn generate
