#!/usr/bin/env bash

set -e

GO111MODULE=off go get golang.org/x/tools/cmd/goimports
go generate ./...
if [[ -n ${CIRCLECI-} ]]; then
  ~/go/bin/goimports -w -local github.com/cmsgov/easi-app pkg/graph/schema.resolvers.go
else
  goimports -w -local github.com/cmsgov/easi-app pkg/graph/schema.resolvers.go
fi
yarn generate
