#!/usr/bin/env bash
#

set -eu -o pipefail

case "$APP_ENV" in
  "dev")
    EASI_URL="https://dev.easi.cms.gov"
    export VITE_OKTA_DOMAIN="https://test.idp.idm.cms.gov"
    ;;
  "impl")
    EASI_URL="https://impl.easi.cms.gov"
    export VITE_OKTA_DOMAIN="https://impl.idp.idm.cms.gov"
    ;;
  "prod")
    EASI_URL="https://easi.cms.gov"
    export VITE_OKTA_DOMAIN="https://idm.cms.gov"
    ;;
  *)
    echo "APP_ENV value not recognized: ${APP_ENV:-unset}"
    echo "Allowed values: 'dev', 'impl', 'prod'"
    exit 1
    ;;
esac

export VITE_OKTA_CLIENT_ID="$OKTA_CLIENT_ID"
export VITE_OKTA_SERVER_ID="$OKTA_SERVER_ID"
export VITE_LD_CLIENT_ID="$LD_CLIENT_ID"
export VITE_APP_ENV="$APP_ENV"
export VITE_OKTA_ISSUER="${VITE_OKTA_DOMAIN}/oauth2/${VITE_OKTA_SERVER_ID}"
export VITE_OKTA_REDIRECT_URI="${EASI_URL}/implicit/callback"
export VITE_API_ADDRESS="${EASI_URL}/api/v1"
export VITE_GRAPHQL_ADDRESS="${EASI_URL}/api/graph/query"

# Check if we have any access to the s3 bucket
# Since `s3 ls` returns zero even if the command failed, we assume failure if this command prints anything to stderr
s3_err="$(aws s3 ls "$STATIC_S3_BUCKET" 1>/dev/null 2>&1)"
if [[ -z "$s3_err" ]] ; then
  ( set -x -u ;
    yarn install --frozen-lockfile
    yarn run build || exit
    aws s3 sync --no-progress --delete build/ s3://"$STATIC_S3_BUCKET"/
  )
else
  echo "+ aws s3 ls $STATIC_S3_BUCKET"
  echo "$s3_err"
  echo "--"
  echo "Error reading the S3 bucket. Are you authenticated?" 1>&2
  exit 1
fi

