#!/usr/bin/env bash
#
# Restart ECS service
#

if [[ "$APP_ENV" != "prod" ]] ; then
  url_prefix="${APP_ENV}."
fi

healthcheck_url="https://${url_prefix}easi.cms.gov/api/v1/healthcheck"
healthcheck_timeout="180"

cluster_name="${APP_ENV}-easi-app"
service_name="easi-app"

# we remove the list of service events since it is verbose and rarely needed when reviewing logs in CI
( set -x ; aws ecs update-service --cluster "$cluster_name" --service "$service_name" --force-new-deployment ) | jq '.service.events = ["REMOVED"]'

# wait for the new service to come up
echo -n "Waiting for health check version to match new deployment on ${healthcheck_url}" 1>&2
until [[ "$(jq --raw-output --monochrome-output .version < <(curl --silent --show-error --location "$healthcheck_url"))" == "$CIRCLE_SHA1" ]] ; do
  if ((++time > healthcheck_timeout)) ; then
    # we timed out
    echo ""
    echo "FATAL: Timed out waiting." 1>&2
    exit 1
  else
    [[ $((time % 10)) -eq 0 ]] && echo -n "."
    sleep 1
  fi
done
echo ""
