#!/usr/bin/env bash

set -ex

docker-compose -f docker-compose.yml -f docker-compose.circleci.yml -f docker-compose.local.yml down
docker-compose -f docker-compose.yml -f docker-compose.circleci.yml -f docker-compose.local.yml build --parallel db_migrate easi easi_client
docker-compose -f docker-compose.yml -f docker-compose.circleci.yml -f docker-compose.local.yml up -d db db_migrate
docker-compose -f docker-compose.yml -f docker-compose.circleci.yml -f docker-compose.local.yml up easi easi_client
