#!/usr/bin/env bash

set -eu -o pipefail

docker-compose build --parallel

docker-compose up -d db
sleep 5
docker-compose up --exit-code-from db_migrate db_migrate
docker-compose up -d easi easilocal
docker-compose up --exit-code-from cypress cypress

# docker container cp easi-app_cypress_1:/cypress/videos cypress/

echo "done!"
