#!/usr/bin/env bash

set -eu -o pipefail

PREFIX="easi-app"
if [ -n "${CIRCLECI+x}" ]; then
  PREFIX="project"
fi

CONTAINER_FRONTEND="${PREFIX}_easilocal"
CONTAINER_CYPRESS="${PREFIX}_cypress"

# Build the frontend and cypress images
docker-compose build \
  --parallel \
  --build-arg REACT_APP_OKTA_CLIENT_ID="$OKTA_CLIENT_ID_DEV" \
  --build-arg REACT_APP_OKTA_DOMAIN="$OKTA_DOMAIN" \
  --build-arg REACT_APP_OKTA_ISSUER="$OKTA_ISSUER" \
  --build-arg REACT_APP_OKTA_REDIRECT_URI=http://localhost:3000/implicit/callback \
  --build-arg REACT_APP_OKTA_SERVER_ID="$OKTA_SERVER_ID_DEV" \
  easilocal \
  cypress

# Run the frontend container
docker container run -d --entrypoint /usr/local/bin/serve --name "$CONTAINER_FRONTEND" "$CONTAINER_FRONTEND":latest -s -l 3000

# Run the cypress container. Connect to frontend container network so cypress can communicate with it using localhost.
docker container run -e OKTA_TEST_USERNAME -e OKTA_TEST_PASSWORD -e OKTA_TEST_SECRET --network container:"$CONTAINER_FRONTEND" --name "$CONTAINER_CYPRESS" "$CONTAINER_CYPRESS":latest

# Stop the frontend container
docker container stop "$CONTAINER_FRONTEND"

# Grab the exit code from the test container
EXIT_STATUS=$(docker inspect "$CONTAINER_CYPRESS" --format='{{.State.ExitCode}}')

# Exit with the status from tests
exit "$EXIT_STATUS"
