#!/usr/bin/env bash

set -eu -o pipefail

PROJECT_NAME=easi-app
CYPRESS_CONTAINER="${PROJECT_NAME}"_cypress_1
EASI_CONTAINER="${PROJECT_NAME}"_easi_1

SERVER_CERT="$(cat ./config/tls/devlocal-https.crt)"
SERVER_KEY="$(cat ./config/tls/devlocal-https.key)"
export SERVER_CERT
export SERVER_KEY

# Running in CI
if [[ -n "${CI+x}" ]]; then
  docker-compose --project-name "${PROJECT_NAME}" -f docker-compose.yml -f docker-compose.github_actions.yml pull db_migrate easi

  docker-compose --project-name "${PROJECT_NAME}" -f docker-compose.yml -f docker-compose.github_actions.yml build --parallel

  docker-compose --project-name "${PROJECT_NAME}" -f docker-compose.yml -f docker-compose.github_actions.yml up -d db
  docker-compose --project-name "${PROJECT_NAME}" -f docker-compose.yml -f docker-compose.github_actions.yml up --exit-code-from db_migrate db_migrate
  docker-compose --project-name "${PROJECT_NAME}" -f docker-compose.yml -f docker-compose.github_actions.yml up --exit-code-from db_seed db_seed
  docker-compose --project-name "${PROJECT_NAME}" -f docker-compose.yml -f docker-compose.github_actions.yml up -d minio
  docker-compose --project-name "${PROJECT_NAME}" -f docker-compose.yml -f docker-compose.github_actions.yml up --exit-code-from minio_mc minio_mc
  docker-compose --project-name "${PROJECT_NAME}" -f docker-compose.yml -f docker-compose.github_actions.yml up -d easi easi_client

  docker-compose --project-name "${PROJECT_NAME}" -f docker-compose.yml -f docker-compose.github_actions.yml up cypress

  docker container cp "${CYPRESS_CONTAINER}":/cypress/screenshots cypress/ || echo "No cypress screenshots copied"
  docker container cp "${CYPRESS_CONTAINER}":/cypress/videos cypress/ || echo "No cypress videos copied"
  CYPRESS_EXIT_CODE=$(docker container inspect --format='{{.State.ExitCode}}' "${CYPRESS_CONTAINER}")
  echo "done"
  exit "${CYPRESS_EXIT_CODE}"
# Running locally
else
  # Clean up first
  docker-compose --project-name "${PROJECT_NAME}" -f docker-compose.yml -f docker-compose.cypress_local.yml down

  docker-compose --project-name "${PROJECT_NAME}" -f docker-compose.yml -f docker-compose.cypress_local.yml build --parallel

  docker-compose --project-name "${PROJECT_NAME}" -f docker-compose.yml -f docker-compose.cypress_local.yml up -d minio minio_mc
  docker-compose --project-name "${PROJECT_NAME}" -f docker-compose.yml -f docker-compose.cypress_local.yml up -d db db_migrate
  docker-compose --project-name "${PROJECT_NAME}" -f docker-compose.yml -f docker-compose.cypress_local.yml up -d db_seed
  docker-compose --project-name "${PROJECT_NAME}" -f docker-compose.yml -f docker-compose.cypress_local.yml up -d easi easi_client

  EASI_EXIT_CODE=$(docker container inspect --format='{{.State.ExitCode}}' "${EASI_CONTAINER}")

  if [[ "${EASI_EXIT_CODE}" -ne 0 ]]; then
    echo "Docker container ${EASI_CONTAINER} exited unexpectedly. No tests will be run."
    docker-compose --project-name "${PROJECT_NAME}" -f docker-compose.yml -f docker-compose.cypress_local.yml logs --tail="all" easi
    exit 1
  fi

  docker-compose --project-name "${PROJECT_NAME}" -f docker-compose.yml -f docker-compose.cypress_local.yml up cypress

  CYPRESS_EXIT_CODE=$(docker container inspect --format='{{.State.ExitCode}}' "${CYPRESS_CONTAINER}")

  # Clean up
  docker-compose --project-name "${PROJECT_NAME}" -f docker-compose.yml -f docker-compose.cypress_local.yml down

  exit "${CYPRESS_EXIT_CODE}"
fi
