#!/bin/bash

set -eu -o pipefail
# set -x

bucket_and_file=$1
tag=$2

if [[ "$tag" != "CLEAN" ]] && [[ "$tag" != "INFECTED" ]] && [[ -n "$tag" ]]; then
    echo "tag must be CLEAN, INFECTED, or blank."
    exit 1
fi

# mc_commands=

# docker-compose run --entrypoint="mc alias set local http://minio:9000 minioadmin minioadmin" minio_mc
# docker-compose run --entrypoint="mc tag set local$bucket_and_file av-status=$tag" minio_mc

# Check if docker-compose is installed
if ! command -v docker-compose &> /dev/null
then
  # if it's not installed, we're running inside Cypress container, use mc binary (installed in Dockerfile)
  /mc tag set "local$bucket_and_file" "av-status=$tag"
else
  # docker-compose exists, so we're running on host (presumably on a local machine, not CI), so use existing minio_mc service
  docker-compose run --entrypoint="mc tag set local$bucket_and_file av-status=$tag" minio_mc
fi
