#!/bin/bash

# usage: scripts/tag_minio_file /bucket/file tag
#
# This script marks a file in minio as having the provided av-status.
# CLEAN, INFECTED, and "" are valid values.

set -eu -o pipefail

bucket_and_file=$1
tag=$2

if [[ "$tag" != "CLEAN" ]] && [[ "$tag" != "INFECTED" ]] && [[ -n "$tag" ]]; then
    echo "tag must be CLEAN, INFECTED, or blank."
    exit 1
fi

# Check if docker compose is installed
if command -v docker compose &> /dev/null
then
  # docker compose exists, so we're running on the host machine instead of in a container (presumably on a local machine, not CI),
  # so use the existing minio_mc service
  docker compose run --entrypoint="mc tag set local$bucket_and_file av-status=$tag" minio_mc
else
  # docker compose isn't installed, so we're running inside the Cypress container,
  # so use the mc binary (installed in Dockerfile.cypress)
  /mc tag set "local$bucket_and_file" "av-status=$tag"
fi
