#!/bin/bash

set -eu -o pipefail
# set -x

bucket_and_file=$1
tag=$2

if [[ "$tag" != "CLEAN" ]] && [[ "$tag" != "INFECTED" ]] && [[ -n "$tag" ]]; then
    echo "tag must be CLEAN, INFECTED, or blank."
    exit 1
fi

# mc_commands=

# docker-compose run --entrypoint="mc alias set local http://minio:9000 minioadmin minioadmin" minio_mc
docker-compose run --entrypoint="mc tag set local$bucket_and_file av-status=$tag" minio_mc
