import { initialSystemIntakeForm, isIntakeStarted } from './systemIntake';

describe('isIntakeStarted', () => {
  it('returns initial data as not started', () => {
    expect(isIntakeStarted(initialSystemIntakeForm)).toEqual(false);
  });

  it('returns data generated by backend as not started', () => {
    const data = {
      ...initialSystemIntakeForm,
      id: '12345',
      requester: {
        name: 'Bob',
        component: '',
        email: ''
      },
      status: 'INTAKE_DRAFT'
    };

    expect(isIntakeStarted(data)).toEqual(false);
  });

  it('returns any filled out fields as started', () => {
    const data = {
      ...initialSystemIntakeForm,
      businessOwner: {
        name: 'Bob',
        component: 'OIT'
      }
    };
    expect(isIntakeStarted(data)).toEqual(true);
  });
});
