name: antivirus

on: workflow_dispatch

jobs: 
  anti_virus:
      runs-on: ubuntu-latest
      steps:
        - run: apt-get update && apt-get install -y clamav curl git ssh
        - name: Check out code
          uses: actions/checkout@1e204e9a9253d643386038d443f96446fa156a97 # v2.3.4
          with:
            ref: ${{ github.event.pull_request.head.sha }}
        - run: clamscan --version
        - run: mkdir -p /store && chown clamav /store
        - run: freshclam --config-file /etc/clamav/freshclam.conf --datadir=/store
        - run: >
            clamscan \
              --recursive \
              --infected \
              --detect-pua=yes \
              --exclude-pua=NetTool \
              --exclude-pua=PWTool \
              --max-scansize=300M \
              --max-filesize=100M \
              --max-recursion=30 \
              --max-files=50000 \
              --tempdir=/tmp \
              --database=/store \
              . \