name: Build Testing Related Docker Images

on:
  workflow_call:
    inputs:
      skip_tests:
        required: false
        type: boolean
        default: false

env:
  GIT_HASH: ${{ github.event.pull_request.head.sha || github.sha }}
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  GIT_REF_NAME: ${{ github.event.pull_request.head.ref || github.ref }}

jobs:
  skip_tests:
    environment: test
    if: ${{ inputs.skip_tests == true }}
    runs-on: ubuntu-latest
    steps:
      - name: Skipping tests
        run: |
            echo "Skipping tests!"
  build_easi-client:
    environment: test
    if: ${{ inputs.skip_tests == false }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          ref: ${{ env.GIT_HASH }}
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Download Frontend assets
        uses: actions/download-artifact@v3
        with:
          name: test-frontend-assets
          path: build/
      - name: Build easi_client Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile.client_ci
          push: false
          tags: easi_client:latest
          cache-to: type=gha,mode=max,scope=${{ env.GIT_REF_NAME }}-easi_client
          cache-from: type=gha,scope=${{ env.GIT_REF_NAME }}-easi_client
      - name: Announce failure
        if: ${{ failure() }}
        run: |
          ./scripts/github-action-announce-broken-branch     
  build_db_seed:
    environment: test
    if: ${{ inputs.skip_tests == false }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          ref: ${{ env.GIT_HASH }}
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build db_seed Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile.db_seed
          push: false
          tags: db_seed:latest
          cache-to: type=gha,mode=max,scope=${{ env.GIT_REF_NAME }}-db_seed
          cache-from: type=gha,scope=${{ env.GIT_REF_NAME }}-db_seed
      - name: Announce failure
        if: ${{ failure() }}
        run: |
          ./scripts/github-action-announce-broken-branch 
  build_easi_cypress:
    environment: test
    if: ${{ inputs.skip_tests == false }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          ref: ${{ env.GIT_HASH }}
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build easi_cypress Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile.cypress
          push: false
          tags: easi_cypress:latest
          cache-to: type=gha,mode=max,scope=${{ env.GIT_REF_NAME }}-easi_cypress
          cache-from: type=gha,scope=${{ env.GIT_REF_NAME }}-easi_cypress
      - name: Announce failure
        if: ${{ failure() }}
        run: |
          ./scripts/github-action-announce-broken-branch