name: Deploy branch environment to EKS

on:
  workflow_call:
    inputs:
      namespace:
        required: false
        type: string
    

permissions:
  id-token: write
  contents: read

env:
  GIT_HASH: ${{ github.sha }}

jobs:
  Deploy_to_EKS:
    runs-on: ubuntu-latest
    environment: "dev"
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_TO_ASSUME }}
          aws-region: us-west-2
      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name dev-easi-poc-cluster --region us-west-2
      - name: Deploy to EKS
        run: |
          if [ -z "${{ inputs.namespace }}" ]; then
            . ./scripts/deploy_eks_env.sh -n ${{ inputs.namespace }}
          else
            . ./scripts/deploy_eks_env.sh
          fi
          echo "# EKS Ingress URLs" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- [EASi](http://${EASI_INGRESS})" >> $GITHUB_STEP_SUMMARY
          echo "- [Mailcatcher](http://${EMAIL_INGRESS})" >> $GITHUB_STEP_SUMMARY
          echo "- [Minio Console](http://${MINIO_CONSOLE_INGRESS})" >> $GITHUB_STEP_SUMMARY
