name: Deploy Pipeline

on:
  push:
    branches:
      - main

concurrency:
  group: deploy-pipeline

jobs:
  # This could be broken out into 3 distinct jobs to make it so each deploy only needs it's own assets to be built, rather than
  # ALL envs assets, but right now building the frontend takes far less time than run tests, so this is not a bottleneck.
  Build_Frontend_Assets:
    uses: ./.github/workflows/build_frontend_assets.yml
    secrets: inherit
    strategy:
      matrix:
        env: [dev, impl, prod]
    with:
      env: ${{ matrix.env }}

  Build_Test_Frontend_Assets:
    uses: ./.github/workflows/build_frontend_assets.yml
    secrets: inherit
    with:
      env: test

  Build_Application_Images:
    uses: ./.github/workflows/build_application_images.yml
    secrets: inherit
  
  Build_Cedarproxy_Image:
    uses: ./.github/workflows/build_cedarproxy_image.yml
    secrets: inherit
    with:
      force_cedarproxy: true

  Run_Tests:
    uses: ./.github/workflows/run_tests.yml
    needs: [Build_Application_Images,Build_Test_Frontend_Assets]
    secrets: inherit

  deploy_dev:
    needs: [Run_Tests, Build_Frontend_Assets]
    uses: ./.github/workflows/deploy_to_environment.yml
    with:
      env: dev
      lambda_version: 10
      force_cedarproxy: true # Per EASI-4374, we want to force cedarproxy deployments in the event pipeline deployment is skipped/cancelled
    secrets: inherit

  deploy_impl:
    needs: [deploy_dev, Build_Frontend_Assets]
    uses: ./.github/workflows/deploy_to_environment.yml
    with:
      env: impl
      force_cedarproxy: true # Per EASI-4374, we want to force cedarproxy deployments in the event pipeline deployment is skipped/cancelled
      lambda_version: 9
    secrets: inherit
  
  deploy_prod:
    needs: [deploy_impl, Build_Frontend_Assets]
    uses: ./.github/workflows/deploy_to_environment.yml
    with:
      env: prod
      force_cedarproxy: true # Per EASI-4374, we want to force cedarproxy deployments in the event pipeline deployment is skipped/cancelled
      lambda_version: 8
    secrets: inherit
