name: Deploy Pipeline

on:
  push:
    branches:
      - main

concurrency:
  group: deploy-pipeline

jobs:
  Build_Application_Images:
    uses: ./.github/workflows/build_application_images.yml
    secrets: inherit

  Run_Tests:
    uses: ./.github/workflows/run_tests.yml
    needs: Build_Application_Images
    secrets: inherit

  deploy_dev:
    needs: Run_Tests
    uses: ./.github/workflows/deploy_to_environment.yml
    with:
      env: dev
      lambda_version: 10
    secrets: inherit

  deploy_impl:
    needs: deploy_dev
    uses: ./.github/workflows/deploy_to_environment.yml
    with:
      env: impl
      lambda_version: 9
    secrets: inherit

  deploy_prod:
    needs: deploy_impl
    uses: ./.github/workflows/deploy_to_environment.yml
    with:
      env: prod
      lambda_version: 8
    secrets: inherit
