name: Deploy To EKS

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  banana:
    runs-on: ubuntu-latest
    environment: "dev"
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_TO_ASSUME }}
          aws-region: us-west-2
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name dev-easi-poc-cluster --region us-west-2
      - name: test kubectl
        run: kubectl get nodes -A
