name: Manual Deployment

on:
  workflow_dispatch:
    inputs:
      env:
        required: true
        default: "dev"
        type: choice
        description: Environment to deploy to
        options:
          - dev
          - impl
          - prod
      confirm_production_deploy:
        required: true
        default: false
        type: boolean
        description: Confirm that you want to deploy to production

permissions:
  id-token: write
  contents: read

jobs:
  Build_Application_Images:
    uses: ./.github/workflows/build_application_images.yml
    secrets: inherit

  Run_Tests:
    uses: ./.github/workflows/run_tests.yml
    needs: Build_Application_Images
    secrets: inherit

  deploy_dev:
    needs: Run_Tests
    if: ${{ github.event.inputs.env == 'dev' }}
    uses: ./.github/workflows/deploy_to_environment.yml
    with:
      env: dev
      lambda_version: 10
    secrets: inherit

  deploy_impl:
    needs: Run_Tests
    if: ${{ github.event.inputs.env == 'impl' }}
    uses: ./.github/workflows/deploy_to_environment.yml
    with:
      env: impl
      lambda_version: 9
    secrets: inherit

  deploy_prod:
    needs: Run_Tests
    if: ${{ github.event.inputs.env == 'prod' && github.event.inputs.confirm_production_deploy == true }}
    uses: ./.github/workflows/deploy_to_environment.yml
    with:
      env: prod
      lambda_version: 8
    secrets: inherit
