name: Manual Deployment

on:
  workflow_dispatch:
    inputs:
      env:
        required: true
        default: "dev"
        type: choice
        description: Environment to deploy to
        options:
          - dev
          - impl
          - prod
      skip_tests:
        required: true
        default: false
        type: boolean
        description: Skip tests?
      force_cedarproxy:
        required: true
        default: false
        type: boolean
        description: Rebuild and redeploy Cedarproxy
      confirm_production_deploy:
        required: true
        default: false
        type: boolean
        description: Confirm that you want to deploy to production

permissions:
  id-token: write
  contents: read

jobs:
  Build_Application_Images:
    uses: ./.github/workflows/build_application_images.yml
    secrets: inherit
  
  Build_Cedarproxy_Image:
    if: ${{ inputs.force_cedarproxy == true }}
    uses: ./.github/workflows/build_cedarproxy_image.yml
    secrets: inherit
    with:
      force_cedarproxy: ${{ inputs.force_cedarproxy }}

  Build_Frontend_Assets:
    uses: ./.github/workflows/build_frontend_assets.yml
    secrets: inherit
    with:
      env: ${{ inputs.env }}
  
  Build_Test_Frontend_Assets:
    uses: ./.github/workflows/build_frontend_assets.yml
    secrets: inherit
    with:
      env: test

  Run_Tests:
    uses: ./.github/workflows/run_tests.yml
    needs: [Build_Application_Images, Build_Test_Frontend_Assets]
    secrets: inherit
    with:
      skip_tests: ${{ inputs.skip_tests }}

  deploy_dev:
    needs: [Run_Tests, Build_Frontend_Assets]
    if: ${{ inputs.env == 'dev' }}
    uses: ./.github/workflows/deploy_to_environment.yml
    with:
      env: dev
      lambda_version: 10
      force_cedarproxy: ${{ inputs.force_cedarproxy }}
    secrets: inherit

  deploy_impl:
    needs: [Run_Tests, Build_Frontend_Assets]
    if: ${{ inputs.env == 'impl' }}
    uses: ./.github/workflows/deploy_to_environment.yml
    with:
      env: impl
      lambda_version: 9
      force_cedarproxy: ${{ inputs.force_cedarproxy }}
    secrets: inherit

  deploy_prod:
    needs: [Run_Tests, Build_Frontend_Assets]
    if: ${{ inputs.env == 'prod' && inputs.confirm_production_deploy == true }}
    uses: ./.github/workflows/deploy_to_environment.yml
    with:
      env: prod
      lambda_version: 8
      force_cedarproxy: ${{ inputs.force_cedarproxy }}
    secrets: inherit
