name: restart_impl_ecs_app_service

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

# on:
#   schedule:
#     - cron:  '0 6 * * *' # 2300 PST, 0200 EST

env:
  AWS_DEFAULT_REGION: us-west-2

jobs:
  restart_impl_ecs_app_service:
    runs-on: ubuntu-latest
#    environment: impl
    env:
      APP_ENV: impl
    steps:
      - name: Check out code
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@13d241b293754004c80624b5567555c4a39ffbe3 # v1.5.10
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME_IMPL }}
          role-duration-seconds: 1800
          role-skip-session-tagging: true
      - name: Restart ECS app service
        env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
        run: |
          ./scripts/deploy_service "easi-app" "impl-ecs-manager-docker" "5" ""
      - name: Announce failure
        if: ${{ failure() }}
        run: |
          ./scripts/github-action-announce-broken-branch
